package engine

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/shellcell/snailmail/forge"
	"github.com/shellcell/snailmail/internal/app"
	"github.com/shellcell/snailmail/internal/state"
)

// CIWorkflowRequest asks for a starting point for continuous publication.
type CIWorkflowRequest struct {
	Root string
	// Provider is the CI system to render for. Empty means GitHub Actions, which
	// was the only template before there was a choice.
	Provider string
	// Version is the snailmail release the workflow installs. Empty leaves a
	// placeholder, because a workflow that pinned whatever version generated it
	// would silently pin the wrong one the moment it was regenerated.
	Version string
}

// CIWorkflow writes a pipeline definition that publishes this workspace.
//
// To stdout, never to a file. A workflow carries decisions this cannot make —
// which registry to pull verification images through, which secret names a
// project uses, how several repositories are assembled into one published site —
// and a file the tool owned would be regenerated over an operator's edits. So
// this emits a starting point, the operator commits it, and snailmail never
// touches it again.
//
// What it does derive is what the workspace already says: which signing keys
// need materialising, whether a foreign architecture needs emulation, and
// whether anything is published to a directory that something else must serve.
func CIWorkflow(request CIWorkflowRequest) ([]byte, error) {
	root, err := workspaceRoot(request.Root)
	if err != nil {
		return nil, err
	}
	manifest, err := state.LoadManifest(root)
	if err != nil {
		return nil, err
	}
	version := request.Version
	if version == "" {
		version = "vX.Y.Z"
	}
	facts := ciFacts{
		manifest: manifest, version: version,
		keys:        signingKeyNames(manifest),
		emulated:    emulatedArchitectures(manifest),
		directories: directoryHosts(manifest),
	}
	switch request.Provider {
	case "", forge.ProviderGitHub:
		return githubWorkflow(facts), nil
	case forge.ProviderGitLab:
		return gitlabPipeline(facts), nil
	}
	return nil, fmt.Errorf("no continuous-publication template for %q", request.Provider)
}

// ciFacts is what both templates derive from the workspace. The derivation is
// shared and only the rendering differs, so a workspace cannot be described one
// way to one CI system and another way to another.
type ciFacts struct {
	manifest    state.Manifest
	version     string
	keys        []string
	emulated    []string
	directories []string
}

func githubWorkflow(facts ciFacts) []byte {
	manifest, version := facts.manifest, facts.version
	keys, emulated, directories := facts.keys, facts.emulated, facts.directories

	var out bytes.Buffer
	fmt.Fprintf(&out, `# Publishes every repository in the %s workspace.
#
# Generated by "snailmail ci github" as a starting point. It is yours now:
# snailmail will not rewrite it, and the decisions left below are ones only this
# project can make.
name: publish

on:
  # A producing repository dispatches this after publishing its release assets.
  repository_dispatch:
    types: [release]
  workflow_dispatch:
    inputs:
      repository:
        description: Tool repository to adopt from, as owner/name
        required: false
        type: string
      tag:
        description: Release tag to adopt, such as v1.2.3
        required: false
        type: string
  # Republish after a lock is changed by hand: promote, yank or prune.
  push:
    branches: [main]

permissions:
  contents: read

# Publishing rewrites shared state, so a second run waits rather than racing the
# lock, the ledger and the published branch.
concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          # Publication ledgers are validated against reachable history.
          fetch-depth: 0

      # Installed from the release asset rather than "go install": the module
      # proxy serves a version's first bytes forever, so a moved tag keeps
      # resolving to the code it originally pointed at. SHA256SUMS from the same
      # release is the pin.
      - name: Install snailmail
        env:
          SNAILMAIL_VERSION: %s
        run: |
          set -euo pipefail
          version=${SNAILMAIL_VERSION#v}
          asset="snailmail_${version}_linux_amd64.tar.gz"
          download="https://github.com/shellcell/snailmail/releases/download/${SNAILMAIL_VERSION}"
          curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 \
            --max-time 300 --remote-name-all "${download}/${asset}" "${download}/SHA256SUMS"
          grep -F "  ./${asset}" SHA256SUMS | sed "s|\./||" | sha256sum -c -
          tar -xzf "$asset" snailmail
          install -m 0755 snailmail /usr/local/bin/snailmail
          rm -f "$asset" SHA256SUMS snailmail
          snailmail version
`, manifest.Workspace.Name, version)

	if len(emulated) != 0 {
		fmt.Fprintf(&out, `
      # %s verified by running a real client for that architecture, which a
      # runner cannot execute without emulation registered for it.
      - name: Register emulation for foreign architectures
        run: |
          set -euo pipefail
          sudo apt-get update >/dev/null
          sudo apt-get install -y --no-install-recommends qemu-user-static >/dev/null
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes >/dev/null
`, describeRepositories(emulated, "is", "are"))
	}

	if len(keys) != 0 {
		out.WriteString(ciKeyStep(keys))
	}

	out.WriteString(`
      # Nothing is published here: adopt records desired state, which is then
      # reviewed as a diff and applied below.
      - name: Adopt the release
        env:
          TOOL_REPOSITORY: ${{ github.event.client_payload.repository || inputs.repository }}
          TOOL_TAG: ${{ github.event.client_payload.tag || inputs.tag }}
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          if [ -z "${TOOL_REPOSITORY}" ] || [ -z "${TOOL_TAG}" ]; then
            echo "no release to adopt; republishing current desired state"
            exit 0
          fi
          # TODO: write the script that adopts your producers' release assets,
          # or call "snailmail adopt --sha256 ... --public-origin REPO URL" per
          # artifact. Which repository an asset belongs in, and whether a
          # producer publishes digests for all of them, is project-specific.
          echo "::error::no adoption script configured"
          exit 1

      - name: Commit desired state
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snailmail.toml repos
          if git diff --cached --quiet; then
            echo "desired state unchanged"
          else
            git commit -m "adopt ${TOOL_REPOSITORY:-release} ${TOOL_TAG:-}"
          fi
        env:
          TOOL_REPOSITORY: ${{ github.event.client_payload.repository || inputs.repository }}
          TOOL_TAG: ${{ github.event.client_payload.tag || inputs.tag }}

      # plan refetches any artifact this runner does not have from the origin its
      # lock records, checking each against the committed digest.
      - name: Plan
        run: snailmail plan --out snailmail.snailmail-plan.json
`)
	out.WriteString(ciApplyStep(len(keys) != 0))

	if len(directories) != 0 {
		out.WriteString(ciSiteStep(directories))
	}

	out.WriteString(`
      - name: Push the publication record
        run: |
          set -euo pipefail
          git add --all -- publications deployments 2>/dev/null || true
          if ! git diff --cached --quiet; then
            git commit -m "record publication ${GITHUB_SHA}"
          fi
          git push origin HEAD:main
`)
	return out.Bytes()
}

func ciKeyStep(keys []string) string {
	var out bytes.Buffer
	out.WriteString(`
      # A signed repository needs its private key on the runner. The key store
      # is a directory snailmail reads; the passphrase reaches it through a file
      # rather than an environment variable so it does not appear in a process
      # listing.
      - name: Prepare the signing keys
        env:
          SIGNING_PASSPHRASE: ${{ secrets.SNAILMAIL_KEY_PASSPHRASE }}
`)
	for _, name := range keys {
		secret := ciSecretName(name)
		fmt.Fprintf(&out, "          %s_REF: ${{ vars.%s_REF }}\n", secret, secret)
		fmt.Fprintf(&out, "          %s_MATERIAL: ${{ secrets.%s }}\n", secret, secret)
	}
	out.WriteString(`        run: |
          set -euo pipefail
          store="${HOME}/.local/share/snailmail/private-keys"
          install_key() {
            reference=$1
            material=$2
            label=$3
            if [ -z "${reference}" ] || [ -z "${material}" ]; then
              echo "::error::${label} is signed but its key is not configured"
              exit 1
            fi
            case "${reference}" in
              *..*|/*|*\\*) echo "::error::unsafe ${label} key reference"; exit 1 ;;
            esac
            mkdir -p "${store}/$(dirname "${reference}")"
            install -m 600 /dev/null "${store}/${reference}.asc"
            printf '%s' "${material}" > "${store}/${reference}.asc"
          }
`)
	for _, name := range keys {
		secret := ciSecretName(name)
		fmt.Fprintf(&out, "          install_key \"${%s_REF}\" \"${%s_MATERIAL}\" \"the %s key\"\n", secret, secret, name)
	}
	out.WriteString(`          install -m 600 /dev/null "${RUNNER_TEMP}/snailmail-passphrase"
          printf '%s' "${SIGNING_PASSPHRASE}" > "${RUNNER_TEMP}/snailmail-passphrase"
`)
	return out.String()
}

func ciApplyStep(signed bool) string {
	var out bytes.Buffer
	out.WriteString(`
      # --runner docker so each repository is checked by a real client
      # installing from the built tree, not only parsed.
      #
      # --image-registry because Docker Hub rate-limits anonymous pulls by source
      # address and hosted runners share them, so a publication can fail for a
      # reason that has nothing to do with its packages. Every verification image
      # is digest-pinned, so a mirror serves the same bytes and the pin is
      # unchanged; this picks a different route to them, not different images.
      - name: Apply
`)
	if signed {
		out.WriteString(`        env:
          SNAILMAIL_KEY_PASSPHRASE_FILE: ${{ runner.temp }}/snailmail-passphrase
          IMAGE_REGISTRY: ${{ vars.VERIFICATION_IMAGE_REGISTRY || 'mirror.gcr.io' }}
`)
	} else {
		out.WriteString(`        env:
          IMAGE_REGISTRY: ${{ vars.VERIFICATION_IMAGE_REGISTRY || 'mirror.gcr.io' }}
`)
	}
	out.WriteString(`        run: |
          set -euo pipefail
          snailmail apply --plan snailmail.snailmail-plan.json --runner docker \
              --image-registry "${IMAGE_REGISTRY}"
`)
	return out.String()
}

func ciSiteStep(directories []string) string {
	var out bytes.Buffer
	fmt.Fprintf(&out, `
      # %s into a directory, so something else has to serve it. This
      # assembles one site and pushes it to a branch Pages is configured from.
      #
      # TODO: set the CNAME below, or delete it if the site is served from a
      # github.io address.
      - name: Assemble the site
        run: |
          set -euo pipefail
          rm -rf site && mkdir -p site
          # Each published repository is a symlink to its current managed
          # release, so the copy dereferences: Git stores a symlink as a symlink
          # and Pages would serve it as a text file rather than following it.
          # The glob also skips snailmail's control and staging directories,
          # which are dot-prefixed and must not reach the site.
          for repository in docs/*/; do
              cp -RL "$repository" "site/$(basename "$repository")"
          done
          # Pages runs Jekyll by default, which would drop files beginning with
          # an underscore and rewrite others.
          touch site/.nojekyll
          # echo "packages.example" > site/CNAME
          # The landing page is generated from the locks, so the versions it
          # advertises cannot drift from the ones actually published.
          snailmail site --output site/index.html

      - name: Deploy the site
        run: |
          set -euo pipefail
          # Force-pushed as a single orphan commit, so the published bytes never
          # accumulate in history.
          cd site
          git init -q .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -q -m "publish ${GITHUB_SHA}"
          git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}" HEAD:gh-pages
        env:
          GITHUB_TOKEN: ${{ github.token }}
`, describeRepositories(directories, "publishes", "publish"))
	return out.String()
}

// signingKeyNames lists the keys any repository signs with, so the workflow
// materialises exactly those and no others.
func signingKeyNames(manifest state.Manifest) []string {
	used := make(map[string]bool)
	for _, repository := range manifest.Repositories {
		for _, key := range repository.SigningKeys {
			used[key] = true
		}
	}
	names := make([]string, 0, len(used))
	for name := range used {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// emulatedArchitectures lists the repositories serving an architecture the
// runner cannot execute natively, which is what decides whether the workflow
// needs QEMU registered.
func emulatedArchitectures(manifest state.Manifest) []string {
	var needed []string
	for _, name := range state.RepositoryNames(manifest) {
		repository := manifest.Repositories[name]
		for _, architecture := range repository.Architectures {
			if app.NeedsEmulation(repository.Format, architecture) {
				needed = append(needed, name+" ("+architecture+")")
				break
			}
		}
	}
	return needed
}

func directoryHosts(manifest state.Manifest) []string {
	var local []string
	for _, name := range state.RepositoryNames(manifest) {
		if manifest.Repositories[name].Host.Type == "local" {
			local = append(local, name)
		}
	}
	return local
}

// describeRepositories lists repositories with a verb that agrees with how many
// there are, because a generated comment is read by people.
func describeRepositories(names []string, singular, plural string) string {
	verb := plural
	if len(names) == 1 {
		verb = singular
	}
	return strings.Join(names, ", ") + " " + verb
}

// ciSecretName turns a key name into the shape a workflow secret is written in.
func ciSecretName(key string) string {
	upper := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z':
			return r - 32
		case r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			return r
		default:
			return '_'
		}
	}, key)
	return "SNAILMAIL_KEY_" + upper
}
