package engine

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/shellcell/snailmail/internal/state"
)

// gitlabPipeline renders a .gitlab-ci.yml that publishes this workspace.
//
// Not a translation of the Actions workflow. Four mechanisms differ, and each
// changes the shape rather than the wording:
//
//   - There is no daemon on the runner. GitHub's hosted runners have Docker;
//     GitLab's need it as a service, and client verification runs a real client
//     in a container, so the service is not optional.
//   - Pages publishes a job artifact from a job that must be called "pages",
//     rather than by moving a ref. So the site is assembled into the artifact
//     directory and GitLab switches it, which also means no push to a branch and
//     no orphan commit.
//   - Secrets are CI/CD variables. A key is a file-type variable, which arrives
//     as a path rather than a value, so it never appears in an environment a
//     child process inherits.
//   - Jobs do not share a filesystem, so what one job produces for the next is
//     declared as an artifact.
func gitlabPipeline(facts ciFacts) []byte {
	manifest, version := facts.manifest, facts.version
	publication := publicationParent(manifest)

	var out bytes.Buffer
	fmt.Fprintf(&out, `# Publishes every repository in the %s workspace.
#
# Generated by "snailmail ci gitlab" as a starting point. It is yours now:
# snailmail will not rewrite it, and the decisions left below are ones only this
# project can make.

stages:
  - publish
`, manifest.Workspace.Name)
	if publication != "" {
		out.WriteString("  - pages\n")
	}

	fmt.Fprintf(&out, `
variables:
  SNAILMAIL_VERSION: %s
  # Docker-in-Docker over TLS. Client verification runs a real client for each
  # repository in a container, so a daemon has to be reachable; a GitLab runner
  # does not have one the way a GitHub-hosted runner does.
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: "1"
  DOCKER_CERT_PATH: "/certs/client"
  # Docker Hub rate-limits anonymous pulls by source address and shared runners
  # share them, so a publication can fail for a reason that has nothing to do
  # with its packages. Every verification image is digest-pinned, so a mirror
  # serves the same bytes and the pin is unchanged: this picks a different route
  # to them, not different images.
  VERIFICATION_IMAGE_REGISTRY: mirror.gcr.io

publish:
  stage: publish
  # A glibc image rather than Alpine. The released linux_amd64 binary is built
  # where a C compiler is present, so cgo is enabled and it links against glibc;
  # on a musl image it would not run at all.
  image: ubuntu:24.04
  services:
    - name: docker:29-dind
      alias: docker
  # Publishing rewrites shared state, so a second run waits rather than racing
  # the lock, the ledger and the published branch.
  resource_group: publish
  rules:
    # A producing project triggers this after publishing its release assets,
    # passing TOOL_PROJECT and TOOL_TAG as trigger variables.
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    # Run by hand from the UI, or after a lock is changed by hand to promote,
    # yank or prune.
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script: |
    set -euo pipefail
    apt-get update -qq
    apt-get install -y -qq --no-install-recommends \
      ca-certificates curl git docker.io >/dev/null
    # Installed from the release asset rather than "go install": the module proxy
    # serves a version's first bytes forever, so a moved tag keeps resolving to
    # the code it originally pointed at. SHA256SUMS from the same release is the
    # pin.
    version=${SNAILMAIL_VERSION#v}
    asset="snailmail_${version}_linux_amd64.tar.gz"
    download="https://github.com/shellcell/snailmail/releases/download/${SNAILMAIL_VERSION}"
    curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 \
      --max-time 300 --remote-name-all "${download}/${asset}" "${download}/SHA256SUMS"
    grep -F "  ./${asset}" SHA256SUMS | sed "s|\./||" | sha256sum -c -
    tar -xzf "$asset" snailmail
    install -m 0755 snailmail /usr/local/bin/snailmail
    rm -f "$asset" SHA256SUMS snailmail
    snailmail version
`, version)

	out.WriteString("  script:\n")

	if len(facts.emulated) != 0 {
		fmt.Fprintf(&out, `    # %s verified by running a real client for that architecture, which a
    # runner cannot execute without emulation registered for it. Registered
    # inside the daemon, because that is where the containers run.
    - |
      set -euo pipefail
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes >/dev/null
`, describeRepositories(facts.emulated, "is", "are"))
	}

	if len(facts.keys) != 0 {
		out.WriteString(gitlabKeyScript(facts.keys))
	}

	out.WriteString(`    # Nothing is published here: adopt records desired state, which is then
    # reviewed as a diff and applied below.
    - |
      set -euo pipefail
      if [ -z "${TOOL_PROJECT:-}" ] || [ -z "${TOOL_TAG:-}" ]; then
        echo "no release to adopt; republishing current desired state"
      else
        # TODO: write the script that adopts your producers' release assets, or
        # call "snailmail adopt --sha256 ... --public-origin PROJECT URL" per
        # artifact. Which repository an asset belongs in, and whether a producer
        # publishes digests for all of them, is project-specific.
        echo "no adoption script configured" >&2
        exit 1
      fi
    - |
      set -euo pipefail
      git config user.name "gitlab-ci"
      git config user.email "gitlab-ci@${CI_SERVER_HOST}"
      git add snailmail.toml repos
      if git diff --cached --quiet; then
        echo "desired state unchanged"
      else
        git commit -m "adopt ${TOOL_PROJECT:-release} ${TOOL_TAG:-}"
      fi
    # plan refetches any artifact this runner does not have from the origin its
    # lock records, checking each against the committed digest.
    - snailmail plan --out snailmail.snailmail-plan.json
`)
	out.WriteString(gitlabApplyScript(len(facts.keys) != 0))

	out.WriteString(`    # Pushed with a project access token, because the job token cannot write to
    # a protected default branch.
    #
    # TODO: create a project access token with write_repository, store it as the
    # masked CI/CD variable SNAILMAIL_PUSH_TOKEN, and allow it to push to the
    # default branch.
    - |
      set -euo pipefail
      git add --all -- publications deployments 2>/dev/null || true
      if ! git diff --cached --quiet; then
        git commit -m "record publication ${CI_COMMIT_SHA}"
      fi
      remote="https://oauth2:${SNAILMAIL_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
      git push "${remote}" "HEAD:${CI_DEFAULT_BRANCH}"
`)

	if publication != "" {
		// Jobs do not share a filesystem. What apply built has to travel to the
		// pages job as an artifact, or that job would serve whatever the checkout
		// happened to contain rather than what was just published.
		fmt.Fprintf(&out, `  artifacts:
    # The built trees, for the pages job. Without this it would serve whatever
    # the checkout contained, which is the previous publication.
    paths:
      - %s/
    expire_in: 1 day
`, publication)
		out.WriteString(gitlabPagesJob(publication, facts.directories))
	}
	return out.Bytes()
}

func gitlabKeyScript(keys []string) string {
	var out bytes.Buffer
	out.WriteString(`    # A signed repository needs its private key on the runner. Each key is a
    # file-type CI/CD variable, so it arrives as a path and its contents are
    # never in an environment a child process inherits. The passphrase is a file
    # for the same reason.
    #
    # TODO: for each key below, add a file-type variable holding the armoured
    # private key, and a variable naming the reference snailmail knows it by.
    - |
      set -euo pipefail
      store="${HOME}/.local/share/snailmail/private-keys"
      install_key() {
        reference=$1
        material_file=$2
        label=$3
        if [ -z "${reference}" ] || [ ! -s "${material_file}" ]; then
          echo "${label} is signed but its key is not configured" >&2
          exit 1
        fi
        case "${reference}" in
          *..*|/*|*\\*) echo "unsafe ${label} key reference" >&2; exit 1 ;;
        esac
        mkdir -p "${store}/$(dirname "${reference}")"
        install -m 600 "${material_file}" "${store}/${reference}.asc"
      }
`)
	for _, name := range keys {
		variable := ciSecretName(name)
		fmt.Fprintf(&out, "      install_key \"${%s_REF:-}\" \"${%s:-/dev/null}\" \"the %s key\"\n",
			variable, variable, name)
	}
	return out.String()
}

func gitlabApplyScript(signed bool) string {
	var out bytes.Buffer
	out.WriteString(`    # --runner docker so each repository is checked by a real client installing
    # from the built tree, not only parsed.
    - |
      set -euo pipefail
`)
	if signed {
		out.WriteString(`      export SNAILMAIL_KEY_PASSPHRASE_FILE="${SNAILMAIL_KEY_PASSPHRASE_FILE:?set it as a file-type variable}"
`)
	}
	out.WriteString(`      snailmail apply --plan snailmail.snailmail-plan.json --runner docker \
          --image-registry "${VERIFICATION_IMAGE_REGISTRY}"
`)
	return out.String()
}

// gitlabPagesJob assembles the site into the artifact directory GitLab serves.
//
// The directory has to be called public, and the repositories are published
// wherever the manifest says, so the two are reconciled here rather than by
// assuming a layout. When they are already the same directory there is nothing
// to copy and copying would mean deleting what was just published.
func gitlabPagesJob(publication string, repositories []string) string {
	var out bytes.Buffer
	fmt.Fprintf(&out, `
# GitLab serves whatever this job publishes as an artifact, and the job has to be
# called "pages". Nothing is pushed to a branch: GitLab switches the deployment,
# which is why there is no orphan-commit dance here.
pages:
  stage: pages
  image: ubuntu:24.04
  needs:
    - job: publish
      artifacts: true
  script:
    - |
      set -euo pipefail
`)
	if publication == "public" {
		fmt.Fprintf(&out, `      # %s already into public/, which is the directory GitLab
      # serves, so the tree is left exactly as apply built it and only the index
      # is added. Clearing it first would delete what was just published.
`, describeRepositories(repositories, "publishes", "publish"))
	} else {
		fmt.Fprintf(&out, `      # %s into %s/, and GitLab serves public/, so the tree is
      # copied across. Each published repository is a symlink to its current
      # managed release, so the copy dereferences: git stores a symlink as a
      # symlink and Pages would serve it as a text file rather than following it.
      rm -rf public && mkdir -p public
      for repository in %s/*/; do
          cp -RL "$repository" "public/$(basename "$repository")"
      done
`, describeRepositories(repositories, "publishes", "publish"), publication, publication)
	}
	out.WriteString(`      # The landing page is generated from the locks, so the versions it
      # advertises cannot drift from the ones actually published.
      snailmail site --output public/index.html
  artifacts:
    paths:
      - public
`)
	return out.String()
}

// publicationParent is the directory local repositories are published under, or
// empty when nothing is published to a directory or they disagree about where.
//
// Disagreement is not an error here the way it is for `snailmail site`: this
// generates a starting point, and a workspace whose repositories are published
// under different parents needs a site job written by hand rather than a refusal
// to emit the rest of the pipeline.
func publicationParent(manifest state.Manifest) string {
	parent := ""
	for _, name := range state.RepositoryNames(manifest) {
		repository := manifest.Repositories[name]
		if repository.Host.Type != "local" {
			continue
		}
		candidate := filepath.ToSlash(filepath.Dir(filepath.Clean(repository.Host.Path)))
		if candidate == "." || candidate == "/" || strings.HasPrefix(candidate, "..") {
			return ""
		}
		if parent == "" {
			parent = candidate
			continue
		}
		if candidate != parent {
			return ""
		}
	}
	return parent
}
