package deb

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"runtime"
	"testing"
	"time"

	"github.com/shellcell/snailmail/internal/domain"
)

// How much memory does rendering a Packages index cost as a repository grows?
//
// A format returns its generated files as bytes, so this is the ceiling on how
// large a repository can be built. Measured: about 415 bytes of index per
// package, and a heap roughly 4.5 times that because the gzip copy and the
// intermediate buffers are live at the same time. 50,000 packages costs 94 MB,
// which puts the ceiling somewhere past a few hundred thousand — far enough that
// streaming the index to disk is not yet worth what it would cost in the build
// graph. Run this before deciding otherwise.
func BenchmarkIndexScale(b *testing.B) {
	for _, count := range []int{1000, 10000, 50000} {
		blobs := make([]domain.Blob, 0, count)
		for i := range count {
			name := fmt.Sprintf("package-%06d", i)
			digest := sha256.Sum256([]byte(name))
			blobs = append(blobs, domain.Blob{
				Filename: name + "_1.0.0_amd64.deb", Size: 6071936,
				MD5:    hex.EncodeToString(digest[:16]),
				SHA1:   hex.EncodeToString(digest[:20]),
				SHA256: hex.EncodeToString(digest[:]),
				Facts: domain.PackageFacts{
					Name: name, Version: "1.0.0", Architecture: "amd64", InstalledSize: 12000000,
					Fields: map[string]string{
						"Package": name, "Version": "1.0.0", "Architecture": "amd64",
						"Maintainer": "Test <t@example.test>", "Description": "a package",
					},
				},
			})
		}
		var before, after runtime.MemStats
		runtime.GC()
		runtime.ReadMemStats(&before)
		start := time.Now()
		artifact, err := Build(blobs, BuildOptions{
			Suite: "stable", Component: "main", Architectures: []string{"amd64"},
			GeneratedAt: time.Unix(1700000000, 0).UTC(),
		})
		if err != nil {
			b.Fatal(err)
		}
		elapsed := time.Since(start)
		runtime.ReadMemStats(&after)
		var generated int64
		for _, file := range artifact.Files {
			generated += int64(len(file.Content))
		}
		b.Logf("%6d packages  render %6.0fms  generated bytes %6.1f MB  heap +%5.0f MB",
			count, float64(elapsed.Milliseconds()), float64(generated)/1e6,
			float64(after.HeapAlloc-before.HeapAlloc)/1e6)
	}
}
