package deb

import (
	"bytes"
	"testing"

	"github.com/shellcell/snailmail/internal/testutil"
)

func TestInspectPackage(t *testing.T) {
	content, filename, err := testutil.Deb("snail-demo", "1.2.3-1", "amd64", []string{"libc6 (>= 2.36)"})
	if err != nil {
		t.Fatal(err)
	}
	facts, err := Inspect(filename, bytes.NewReader(content), int64(len(content)))
	if err != nil {
		t.Fatal(err)
	}
	if facts.Name != "snail-demo" || facts.Version != "1.2.3-1" || facts.Architecture != "amd64" {
		t.Fatalf("unexpected package facts: %#v", facts)
	}
	if facts.Fields["Depends"] != "libc6 (>= 2.36)" {
		t.Fatalf("unexpected dependency field: %#v", facts.Fields)
	}
	if facts.Fields["Description"] != "deterministic test package\ngenerated by snailmail tests" {
		t.Fatalf("unexpected multiline description: %q", facts.Fields["Description"])
	}
}

func TestInspectRejectsInvalidArchive(t *testing.T) {
	content := []byte("not a deb")
	if _, err := Inspect("broken.deb", bytes.NewReader(content), int64(len(content))); err == nil {
		t.Fatal("expected invalid package to fail")
	}
}

func TestInspectRequiresDataArchive(t *testing.T) {
	content, filename, err := testutil.Deb("snail-demo", "1.2.3-1", "amd64", nil)
	if err != nil {
		t.Fatal(err)
	}
	dataHeader := bytes.Index(content, []byte("data.tar.gz/"))
	if dataHeader < 0 {
		t.Fatal("fixture has no data archive")
	}
	content = content[:dataHeader]
	if _, err := Inspect(filename, bytes.NewReader(content), int64(len(content))); err == nil {
		t.Fatal("expected missing data archive to fail")
	}
}

func TestInspectRejectsInvalidVersion(t *testing.T) {
	content, filename, err := testutil.Deb("snail-demo", "release-one", "amd64", nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Inspect(filename, bytes.NewReader(content), int64(len(content))); err == nil {
		t.Fatal("expected invalid Debian version to fail")
	}
}

func TestValidVersionRejectsEmptyRevision(t *testing.T) {
	if validVersion("1.2.3-") {
		t.Fatal("version with an empty Debian revision was accepted")
	}
}

func TestParseControlRejectsCaseFoldedDuplicateAndControlByte(t *testing.T) {
	if _, err := parseControl([]byte("Package: one\npackage: two\n")); err == nil {
		t.Fatal("case-insensitive duplicate field was accepted")
	}
	if _, err := parseControl([]byte("Package: one\nDescription: bad\x01value\n")); err == nil {
		t.Fatal("control byte in field value was accepted")
	}
}

func FuzzInspect(f *testing.F) {
	content, filename, err := testutil.Deb("snail-demo", "1.2.3-1", "amd64", nil)
	if err != nil {
		f.Fatal(err)
	}
	f.Add(filename, content)
	f.Add("broken.deb", []byte("not a package"))
	f.Fuzz(func(t *testing.T, name string, raw []byte) {
		if int64(len(raw)) > MaxArtifactSize {
			t.Skip()
		}
		_, _ = Inspect(name, bytes.NewReader(raw), int64(len(raw)))
	})
}

// Every package dpkg builds leads its archives with a "./" entry, and this
// inspector refused it as traversal. Nothing caught it because the fixtures
// were the only packages the format ever saw and none of them had one; the
// fixtures now write it, so the rest of the suite covers this too. Verified
// against a real archive package: hello_2.10-3build1 has the same entry.
func TestInspectAcceptsTheArchiveRootEntry(t *testing.T) {
	content, filename, err := testutil.Deb("snail-demo", "1.2.3-1", "amd64", nil)
	if err != nil {
		t.Fatal(err)
	}
	facts, err := Inspect(filename, bytes.NewReader(content), int64(len(content)))
	if err != nil {
		t.Fatalf("a package with a \"./\" entry was refused: %v", err)
	}
	if facts.Name != "snail-demo" || facts.Version != "1.2.3-1" {
		t.Fatalf("got %s@%s", facts.Name, facts.Version)
	}
}
