package app

import (
	"bytes"
	"context"
	"crypto/md5"
	"crypto/sha1"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/shellcell/snailmail/formats/deb"
	"github.com/shellcell/snailmail/formats/helm"
	"github.com/shellcell/snailmail/formats/pypi"
	"github.com/shellcell/snailmail/formats/raw"
	"github.com/shellcell/snailmail/host"
	"github.com/shellcell/snailmail/internal/buildgraph"
	"github.com/shellcell/snailmail/internal/domain"
	"github.com/shellcell/snailmail/internal/factscache"
	"github.com/shellcell/snailmail/internal/listing"
	openpgpsigner "github.com/shellcell/snailmail/signer/openpgp"
)

const (
	maxManifestSize    = 8 << 20
	maxRepositoryFiles = 20_000
	maxRepositoryBytes = 4 << 30
)

// VerifyRepository checks the management manifest and every generated byte.
func VerifyRepository(root string) (buildgraph.RepositoryManifest, error) {
	manifest, _, err := verifyRepository(root)
	return manifest, err
}

func verifyRepository(root string) (buildgraph.RepositoryManifest, []domain.Blob, error) {
	absolute, err := filepath.Abs(root)
	if err != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("resolve repository: %w", err)
	}
	absolute, err = filepath.EvalSymlinks(absolute)
	if err != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("resolve repository release: %w", err)
	}
	manifestPath := filepath.Join(absolute, buildgraph.ManifestFilename)
	manifestFile, err := os.Open(manifestPath)
	if err != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("open repository manifest: %w", err)
	}
	manifestBytes, readErr := io.ReadAll(io.LimitReader(manifestFile, maxManifestSize+1))
	closeErr := manifestFile.Close()
	if readErr != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("read repository manifest: %w", readErr)
	}
	if closeErr != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("close repository manifest: %w", closeErr)
	}
	if len(manifestBytes) > maxManifestSize {
		return buildgraph.RepositoryManifest{}, nil, errors.New("repository manifest exceeds 8 MiB")
	}
	decoder := json.NewDecoder(bytes.NewReader(manifestBytes))
	decoder.DisallowUnknownFields()
	var manifest buildgraph.RepositoryManifest
	if err := decoder.Decode(&manifest); err != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("decode repository manifest: %w", err)
	}
	if err := requireJSONEOF(decoder); err != nil {
		return buildgraph.RepositoryManifest{}, nil, err
	}
	if !buildgraph.SupportedManifestSchema(manifest.SchemaVersion) {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("unsupported repository schema %d", manifest.SchemaVersion)
	}
	if manifest.Format == "" {
		return buildgraph.RepositoryManifest{}, nil, errors.New("repository manifest has no format")
	}
	if _, err := time.Parse(time.RFC3339, manifest.GeneratedAt); err != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("invalid generation time: %w", err)
	}
	if len(manifest.Files) > maxRepositoryFiles {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("repository has more than %d files", maxRepositoryFiles)
	}
	var repositorySize int64
	for _, file := range manifest.Files {
		if file.Size < 0 || file.Size > maxRepositoryBytes-repositorySize {
			return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("repository exceeds the %d byte verification limit", maxRepositoryBytes)
		}
		repositorySize += file.Size
	}

	expected := map[string]bool{buildgraph.ManifestFilename: true}
	for index, file := range manifest.Files {
		if err := validateManifestFile(file, index, manifest.Files); err != nil {
			return buildgraph.RepositoryManifest{}, nil, err
		}
		expected[file.Path] = true
		actualSize, actualHash, err := hashRepositoryFile(absolute, file.Path)
		if err != nil {
			return buildgraph.RepositoryManifest{}, nil, err
		}
		if actualSize != file.Size || actualHash != file.SHA256 {
			return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("repository file %q does not match its manifest", file.Path)
		}
	}
	if buildgraph.TreeDigest(manifest.Files) != manifest.TreeSHA256 {
		return buildgraph.RepositoryManifest{}, nil, errors.New("repository tree digest does not match its manifest")
	}
	if err := rejectUnexpectedFiles(absolute, expected); err != nil {
		return buildgraph.RepositoryManifest{}, nil, err
	}
	var blobs []domain.Blob
	if manifest.Format == pypi.FormatID {
		blobs, err = verifyPyPIStructure(absolute, manifest)
		if err != nil {
			return buildgraph.RepositoryManifest{}, nil, err
		}
	}
	if manifest.Format == deb.FormatID {
		blobs, err = verifyDebStructure(absolute, manifest)
		if err != nil {
			return buildgraph.RepositoryManifest{}, nil, err
		}
	}
	if manifest.Format == helm.FormatID {
		blobs, err = verifyHelmStructure(absolute, manifest)
		if err != nil {
			return buildgraph.RepositoryManifest{}, nil, err
		}
	}
	if manifest.Format == raw.FormatID {
		blobs, err = verifyRawStructure(absolute, manifest)
		if err != nil {
			return buildgraph.RepositoryManifest{}, nil, err
		}
	}
	return manifest, blobs, nil
}

// VerifyPyPIClient installs every unique project version with pip from an
// ephemeral HTTP server over the verified tree.
func VerifyPyPIClient(ctx context.Context, root, python string) (buildgraph.RepositoryManifest, int, error) {
	release, err := filepath.Abs(root)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository: %w", err)
	}
	release, err = filepath.EvalSymlinks(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository release: %w", err)
	}
	manifest, _, err := verifyRepository(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	snapshot, err := snapshotRepository(ctx, release, manifest)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	defer os.RemoveAll(snapshot)
	manifest, blobs, err := verifyRepository(snapshot)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	if manifest.Format != pypi.FormatID {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("repository format is %q, not %q", manifest.Format, pypi.FormatID)
	}
	server := httptest.NewServer(http.FileServer(http.Dir(snapshot)))
	defer server.Close()
	installed, err := verifyPyPICases(ctx, manifest, blobs, server.URL, python, "", "", false)
	return manifest, installed, err
}

// VerifyPyPIClientEndpoint verifies the local immutable tree but installs from
// the host-served endpoint, proving staged or canonical HTTP behavior.
func VerifyPyPIClientEndpoint(ctx context.Context, root, endpoint, python string) (buildgraph.RepositoryManifest, int, error) {
	return VerifyPyPIClientEndpointAccess(ctx, root, host.ClientAccess{Endpoint: endpoint}, python)
}

func VerifyPyPIClientEndpointAccess(ctx context.Context, root string, access host.ClientAccess, python string) (buildgraph.RepositoryManifest, int, error) {
	if access.Credential != nil {
		defer access.Credential.Destroy()
	}
	if _, err := validateClientEndpoint(access.Endpoint); err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	var err error
	username, password := "", ""
	private := access.Credential != nil
	if private {
		username, password, err = access.Credential.Basic(ctx)
		if err != nil {
			return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve private repository credential: %w", err)
		}
		if !validNetrcValue(username) || !validNetrcValue(password) {
			return buildgraph.RepositoryManifest{}, 0, errors.New("private repository credential is not safe for netrc injection")
		}
	}
	manifest, blobs, err := verifyRepository(root)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	if manifest.Format != pypi.FormatID {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("repository format is %q, not %q", manifest.Format, pypi.FormatID)
	}
	if len(access.Routes) == 0 {
		access.Routes, err = defaultClientRoutes(access.Endpoint, manifest.Files)
		if err != nil {
			return buildgraph.RepositoryManifest{}, 0, err
		}
	}
	if err := awaitHostedBytes(ctx, access, username, password, private); err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	installed, err := verifyPyPICases(ctx, manifest, blobs, strings.TrimSuffix(access.Endpoint, "/"), python, username, password, private)
	return manifest, installed, err
}

func verifyPyPICases(ctx context.Context, manifest buildgraph.RepositoryManifest, blobs []domain.Blob, endpoint, python, username, password string, private bool) (int, error) {
	parsedEndpoint, err := url.Parse(endpoint)
	if err != nil || parsedEndpoint.Hostname() == "" {
		return 0, errors.New("invalid PyPI verification endpoint")
	}
	noProxy := strings.Join([]string{parsedEndpoint.Hostname(), "127.0.0.1", "localhost"}, ",")
	if python == "" {
		python = "python3"
	}
	resolvedPython, err := exec.LookPath(python)
	if err != nil {
		return 0, fmt.Errorf("find Python client: %w", err)
	}
	python = resolvedPython
	wheels := make(map[string]bool)
	for _, blob := range blobs {
		if strings.HasSuffix(strings.ToLower(blob.Filename), ".whl") {
			wheels[pypi.NormalizeName(blob.Facts.Name)+"\x00"+blob.Facts.Version] = true
		}
		for _, requirement := range blob.Facts.Requirements {
			if strings.Contains(requirement, "@") {
				return 0, fmt.Errorf("host verification rejects direct URL requirement %q; use an isolated runner", requirement)
			}
		}
	}
	verificationCases := manifest.VerificationCases
	emptyProbe := len(verificationCases) == 0
	if emptyProbe {
		verificationCases = []domain.VerificationCase{{Project: "snailmail-empty-probe", Version: "0"}}
	}
	for _, verification := range manifest.VerificationCases {
		if !wheels[verification.Project+"\x00"+verification.Version] {
			return 0, fmt.Errorf("%s==%s has no wheel; source distribution verification requires an isolated runner", verification.Project, verification.Version)
		}
	}
	for _, verification := range verificationCases {
		sandbox, err := os.MkdirTemp("", ".snailmail-pip-*")
		if err != nil {
			return 0, fmt.Errorf("create pip sandbox: %w", err)
		}
		target := filepath.Join(sandbox, "target")
		home := filepath.Join(sandbox, "home")
		temporary := filepath.Join(sandbox, "tmp")
		if err := os.MkdirAll(home, 0o700); err != nil {
			_ = os.RemoveAll(sandbox)
			return 0, err
		}
		if err := os.MkdirAll(temporary, 0o700); err != nil {
			_ = os.RemoveAll(sandbox)
			return 0, err
		}
		if private {
			netrc := []byte("machine " + parsedEndpoint.Hostname() + "\nlogin " + username + "\npassword " + password + "\n")
			if err := os.WriteFile(filepath.Join(home, ".netrc"), netrc, 0o600); err != nil {
				_ = os.RemoveAll(sandbox)
				return 0, err
			}
		}
		arguments := []string{
			"-I", "-m", "pip", "install",
			"--disable-pip-version-check",
			"--no-input",
			"--no-build-isolation",
			"--only-binary=:all:",
			"--no-compile",
			"--index-url", endpoint + "/" + manifest.Install.IndexPath,
			"--target", target,
			"--", verification.Project + "==" + verification.Version,
		}
		command := exec.CommandContext(ctx, python, arguments...)
		command.Dir = sandbox
		command.Env = []string{
			"HOME=" + home,
			"TMPDIR=" + temporary,
			"PATH=" + os.Getenv("PATH"),
			"LANG=C.UTF-8",
			"PIP_CONFIG_FILE=" + os.DevNull,
			"PIP_NO_CACHE_DIR=1",
			"PYTHONNOUSERSITE=1",
			"HTTP_PROXY=http://127.0.0.1:9",
			"HTTPS_PROXY=http://127.0.0.1:9",
			"http_proxy=http://127.0.0.1:9",
			"https_proxy=http://127.0.0.1:9",
			"NO_PROXY=" + noProxy,
			"no_proxy=" + noProxy,
		}
		output, commandErr := command.CombinedOutput()
		if emptyProbe {
			expectedMiss := commandErr != nil && (bytes.Contains(output, []byte("No matching distribution found")) || bytes.Contains(output, []byte("Could not find a version that satisfies")))
			if !expectedMiss {
				if commandErr == nil {
					commandErr = errors.New("empty PyPI repository unexpectedly resolved probe package")
				} else {
					commandErr = fmt.Errorf("empty PyPI client probe did not report an expected package miss: %w", commandErr)
				}
			} else {
				commandErr = nil
			}
		}
		credentialCleanupErr := error(nil)
		if private {
			netrcPath := filepath.Join(home, ".netrc")
			if err := os.WriteFile(netrcPath, nil, 0o600); err != nil {
				credentialCleanupErr = err
			} else if err := os.Remove(netrcPath); err != nil && !errors.Is(err, fs.ErrNotExist) {
				credentialCleanupErr = err
			}
		}
		removeErr := os.RemoveAll(sandbox)
		if commandErr != nil {
			if credentialCleanupErr != nil || removeErr != nil {
				return 0, fmt.Errorf("pip install %s==%s: %w\n%s\ncredential cleanup: %v; sandbox cleanup: %v", verification.Project, verification.Version, commandErr, redactCredential(strings.TrimSpace(string(output)), username, password), credentialCleanupErr, removeErr)
			}
			return 0, fmt.Errorf("pip install %s==%s: %w\n%s", verification.Project, verification.Version, commandErr, redactCredential(strings.TrimSpace(string(output)), username, password))
		}
		if credentialCleanupErr != nil {
			return 0, fmt.Errorf("remove pip credential: %w", credentialCleanupErr)
		}
		if removeErr != nil {
			return 0, fmt.Errorf("remove pip target: %w", removeErr)
		}
	}
	return len(manifest.VerificationCases), nil
}

// validateClientEndpoint accepts only an endpoint a package client may be
// pointed at: no credentials in the URL, no query or fragment, and HTTPS unless
// it is loopback, so verification cannot be satisfied by a plaintext origin an
// attacker controls.
func validateClientEndpoint(endpoint string) (*url.URL, error) {
	parsed, err := url.Parse(endpoint)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" ||
		parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
		return nil, errors.New("verification endpoint must be an HTTP(S) URL")
	}
	if parsed.Scheme != "https" && !isLoopbackHost(parsed.Hostname()) {
		return nil, errors.New("verification endpoint must use HTTPS")
	}
	return parsed, nil
}

// awaitHostedBytes waits for the host to serve exactly the reviewed tree. A
// host that publishes through a CDN or a Pages build is eventually consistent,
// so a first mismatch is retried until the propagation budget runs out; a
// mismatch after that is a real difference, not latency.
func awaitHostedBytes(ctx context.Context, access host.ClientAccess, username, password string, private bool) error {
	deadline := time.Now().Add(access.PropagationTimeout)
	for {
		err := verifyHostedBytes(ctx, access, username, password, private)
		if err == nil {
			return nil
		}
		if access.PropagationTimeout <= 0 || !time.Now().Before(deadline) {
			return err
		}
		timer := time.NewTimer(2 * time.Second)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
	}
}

// verifyHostedBytes checks that every route serves the exact reviewed bytes.
// It is format-neutral: what differs per ecosystem is the client install that
// follows, not whether the host returns the digests that were verified.
func verifyHostedBytes(ctx context.Context, access host.ClientAccess, username, password string, private bool) error {
	endpoint, err := url.Parse(access.Endpoint)
	if err != nil {
		return errors.New("invalid PyPI verification endpoint")
	}
	client := &http.Client{
		Timeout: 30 * time.Second,
		CheckRedirect: func(_ *http.Request, _ []*http.Request) error {
			return errors.New("repository verification does not follow redirects")
		},
	}
	// Routes cover every file in the tree, including distributions up to
	// pypi.MaxArtifactSize. Only the digest and length matter here, so the body
	// is hashed as it streams rather than buffered whole.
	verifyURL := func(address string, expectedSize int64, expectedSHA256 string) error {
		request, err := http.NewRequestWithContext(ctx, http.MethodGet, address, nil)
		if err != nil {
			return err
		}
		if private {
			request.SetBasicAuth(username, password)
		}
		response, err := client.Do(request)
		if err != nil {
			return err
		}
		hash := sha256.New()
		size, readErr := io.Copy(hash, io.LimitReader(response.Body, expectedSize+1))
		closeErr := response.Body.Close()
		if readErr != nil {
			return readErr
		}
		if closeErr != nil {
			return closeErr
		}
		if response.StatusCode != http.StatusOK || size != expectedSize || hex.EncodeToString(hash.Sum(nil)) != expectedSHA256 {
			return errors.New("host-served repository bytes do not match the reviewed tree")
		}
		return nil
	}
	for _, route := range access.Routes {
		parsed, err := url.Parse(route.URL)
		if err != nil || parsed.Scheme != endpoint.Scheme || parsed.Host != endpoint.Host || parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" || route.Size < 0 {
			return errors.New("host supplied an invalid client verification route")
		}
		if err := verifyURL(route.URL, route.Size, route.SHA256); err != nil {
			return fmt.Errorf("verify host-served route %q: %w", parsed.EscapedPath(), err)
		}
	}
	return nil
}

// defaultClientRoutes covers every file in the tree when a host supplies no
// route list of its own. The index-page rewrite is harmless for formats without
// directory indexes, whose paths never end in index.html.
func defaultClientRoutes(endpoint string, files []buildgraph.ManifestFile) ([]host.ClientRoute, error) {
	routes := make([]host.ClientRoute, 0, len(files))
	for _, file := range files {
		routePath := file.Path
		if strings.HasSuffix(routePath, "/index.html") {
			routePath = strings.TrimSuffix(routePath, "index.html")
		}
		address, err := url.JoinPath(strings.TrimSuffix(endpoint, "/")+"/", routePath)
		if err != nil {
			return nil, err
		}
		if strings.HasSuffix(routePath, "/") && !strings.HasSuffix(address, "/") {
			address += "/"
		}
		routes = append(routes, host.ClientRoute{URL: address, Size: file.Size, SHA256: file.SHA256})
	}
	return routes, nil
}

func validNetrcValue(value string) bool {
	if value == "" {
		return false
	}
	if strings.ContainsAny(value, `\"'#`) {
		return false
	}
	for _, character := range value {
		if character <= 0x20 || character == 0x7f {
			return false
		}
	}
	return true
}

func isLoopbackHost(value string) bool {
	return value == "localhost" || value == "127.0.0.1" || value == "::1"
}

func redactCredential(value, username, password string) string {
	// With no credential every derived form is a constant — base64(":") in
	// particular — so redacting them would rewrite unrelated client output.
	if username == "" || password == "" {
		return value
	}
	secrets := []string{
		username, password, url.QueryEscape(username), url.QueryEscape(password),
		base64.StdEncoding.EncodeToString([]byte(username + ":" + password)),
	}
	sort.Slice(secrets, func(left, right int) bool { return len(secrets[left]) > len(secrets[right]) })
	for _, secret := range secrets {
		if secret != "" {
			value = strings.ReplaceAll(value, secret, "[REDACTED]")
		}
	}
	return value
}

// VerifyDebClient resolves and extracts each planned package version in its own
// bounded, network-isolated Debian container.
func VerifyDebClient(ctx context.Context, root, runner, image string, maxWorkspaceBytes int64) (buildgraph.RepositoryManifest, int, error) {
	release, err := filepath.Abs(root)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository: %w", err)
	}
	release, err = filepath.EvalSymlinks(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository release: %w", err)
	}
	manifest, _, err := verifyRepository(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	snapshot, err := snapshotRepository(ctx, release, manifest)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	defer os.RemoveAll(snapshot)
	manifest, blobs, err := verifyRepository(snapshot)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	if manifest.Format != deb.FormatID {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("repository format is %q, not %q", manifest.Format, deb.FormatID)
	}
	if runner == "" {
		runner = "podman"
	}
	runner, err = exec.LookPath(runner)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("find container runner: %w", err)
	}
	if !digestPinnedImage(image) {
		return buildgraph.RepositoryManifest{}, 0, errors.New("a digest-pinned Debian verification image is required")
	}
	workspaceBytes, err := debWorkspaceSize(blobs, maxWorkspaceBytes)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	verificationCases := manifest.VerificationCases
	if len(verificationCases) == 0 {
		for _, architecture := range manifest.Install.Architectures {
			verificationCases = append(verificationCases, domain.VerificationCase{Architecture: architecture})
		}
	}
	for _, verification := range verificationCases {
		if err := verifyDebCase(ctx, runner, image, snapshot, workspaceBytes, manifest, verification); err != nil {
			return buildgraph.RepositoryManifest{}, 0, err
		}
	}
	return manifest, len(manifest.VerificationCases), nil
}

func verifyDebCase(ctx context.Context, runner, image, snapshot string, workspaceBytes int64, manifest buildgraph.RepositoryManifest, verification domain.VerificationCase) error {
	platform, err := debOCIPlatform(verification.Architecture)
	if err != nil {
		return err
	}
	caseCtx, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()
	memoryBytes := workspaceBytes + 512<<20
	reference, platformFlag, err := platformImage(caseCtx, runner, image, platform)
	if err != nil {
		return err
	}
	arguments := []string{"run", "--rm", "--pull=missing", "--network=none"}
	if platformFlag {
		arguments = append(arguments, "--platform", platform)
	}
	arguments = append(arguments,
		"--read-only", "--memory="+strconv.FormatInt(memoryBytes, 10), "--cpus=2", "--pids-limit=256",
		"--ulimit", "fsize=536870912:536870912", "--ulimit", "nofile=1024:1024",
		"--security-opt", "no-new-privileges",
		"--volume", snapshot+":/target/repo:ro,Z",
		"--env", "DEBIAN_FRONTEND=noninteractive",
		"--env", "SNAILMAIL_SUITE="+manifest.Install.Suite,
		"--env", "SNAILMAIL_COMPONENT="+manifest.Install.Component,
		"--env", "SNAILMAIL_ARCHITECTURE="+verification.Architecture,
		"--env", "SNAILMAIL_PACKAGE="+verification.Package,
		"--env", "SNAILMAIL_VERSION="+verification.Version,
		"--env", "SNAILMAIL_SIGNING_KEY="+manifest.Install.SigningKeyPath,
		"--tmpfs", "/tmp:rw,size=64m,mode=1777",
		// exec is explicit because runtimes mount tmpfs noexec by default and the
		// chroot below runs apt-get and dpkg-query out of this mount.
		"--tmpfs", "/target:rw,exec,size="+strconv.FormatInt(workspaceBytes, 10)+",mode=0755",
		reference,
		"sh", "-euc", `
for directory in bin etc lib lib64 sbin usr var; do
    test -e "/$directory" && cp -a "/$directory" /target/
done
mkdir -p /target/dev /target/proc /target/sys /target/tmp
chmod 1777 /target/tmp
: >/target/dev/null
rm -rf /target/etc/apt/sources.list.d/* /target/etc/apt/sources.list
mkdir -p /target/var/lib/apt/lists/partial /target/var/cache/apt/archives/partial
if test -n "$SNAILMAIL_SIGNING_KEY"; then
    printf 'deb [signed-by=/repo/%s arch=%s] file:/repo %s %s\n' "$SNAILMAIL_SIGNING_KEY" "$SNAILMAIL_ARCHITECTURE" "$SNAILMAIL_SUITE" "$SNAILMAIL_COMPONENT" >/target/etc/apt/sources.list
else
    printf 'deb [trusted=yes arch=%s] file:/repo %s %s\n' "$SNAILMAIL_ARCHITECTURE" "$SNAILMAIL_SUITE" "$SNAILMAIL_COMPONENT" >/target/etc/apt/sources.list
fi
chroot /target apt-get -o APT::Sandbox::User=root -o Acquire::Languages=none update
if test -n "$SNAILMAIL_PACKAGE"; then
    chroot /target apt-get -o APT::Sandbox::User=root install -y --reinstall --no-install-recommends "$SNAILMAIL_PACKAGE=$SNAILMAIL_VERSION"
    status=$(chroot /target dpkg-query -W -f='${Status} ${Version}' "$SNAILMAIL_PACKAGE")
    test "$status" = "install ok installed $SNAILMAIL_VERSION"
fi
`)
	command := exec.CommandContext(caseCtx, runner, arguments...)
	command.Env = runnerEnvironment()
	output, err := command.CombinedOutput()
	if err != nil {
		if registryUnavailable(output) {
			return fmt.Errorf("%w: %s", ErrVerificationImageUnavailable, strings.TrimSpace(string(output)))
		}
		if foreignPlatformUnsupported(output) {
			return fmt.Errorf("%w: verifying %s needs QEMU and binfmt_misc registered for it",
				ErrForeignPlatformUnsupported, verification.Architecture)
		}
		return fmt.Errorf("Debian client verification for %s=%s/%s: %w\n%s", verification.Package, verification.Version, verification.Architecture, err, strings.TrimSpace(string(output)))
	}
	return nil
}

func debWorkspaceSize(blobs []domain.Blob, maximum int64) (int64, error) {
	const (
		baseRootBytes = 256 << 20
		minimumBytes  = 768 << 20
	)
	if maximum <= 0 {
		return 0, errors.New("Debian verification workspace limit must be positive")
	}
	required := int64(baseRootBytes)
	for _, blob := range blobs {
		addition := blob.Size + blob.Facts.InstalledSize
		if addition < 0 || required > maximum-addition {
			return 0, fmt.Errorf("Debian verification requires more than the configured %d byte workspace", maximum)
		}
		required += addition
	}
	if required < minimumBytes {
		required = minimumBytes
	}
	if required > maximum {
		return 0, fmt.Errorf("Debian verification requires %d bytes, above the configured %d byte workspace", required, maximum)
	}
	return required, nil
}

func digestPinnedImage(image string) bool {
	digest := ""
	if separator := strings.LastIndex(image, "@sha256:"); separator >= 0 {
		digest = image[separator+len("@sha256:"):]
	} else if strings.HasPrefix(image, "sha256:") {
		digest = strings.TrimPrefix(image, "sha256:")
	}
	if len(digest) != sha256.Size*2 || digest != strings.ToLower(digest) {
		return false
	}
	decoded, err := hex.DecodeString(digest)
	return err == nil && len(decoded) == sha256.Size
}

func debOCIPlatform(architecture string) (string, error) {
	platforms := map[string]string{
		"amd64":    "linux/amd64",
		"arm64":    "linux/arm64",
		"armhf":    "linux/arm/v7",
		"armel":    "linux/arm/v5",
		"i386":     "linux/386",
		"mips64el": "linux/mips64le",
		"ppc64el":  "linux/ppc64le",
		"s390x":    "linux/s390x",
	}
	platform := platforms[architecture]
	if platform == "" {
		return "", fmt.Errorf("no OCI platform mapping for Debian architecture %q", architecture)
	}
	return platform, nil
}

func VerifyHelmClient(ctx context.Context, root, runner, image string) (buildgraph.RepositoryManifest, int, error) {
	release, err := filepath.Abs(root)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository: %w", err)
	}
	release, err = filepath.EvalSymlinks(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository release: %w", err)
	}
	manifest, _, err := verifyRepository(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	snapshot, err := snapshotRepository(ctx, release, manifest)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	defer os.RemoveAll(snapshot)
	manifest, _, err = verifyRepository(snapshot)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	if manifest.Format != helm.FormatID {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("repository format is %q, not %q", manifest.Format, helm.FormatID)
	}
	if runner == "" {
		runner = "podman"
	}
	runner, err = exec.LookPath(runner)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("find container runner: %w", err)
	}
	if !digestPinnedImage(image) {
		return buildgraph.RepositoryManifest{}, 0, errors.New("a digest-pinned Helm verification image is required")
	}
	// Helm needs an HTTP repository, and the pinned image ships no static
	// server: its busybox has no httpd applet and its nc has no -e. Serve the
	// snapshot from here instead, which also removes a shell-scripted HTTP
	// implementation from the trusted path.
	snapshotHTTP, err := serveSnapshot(snapshot)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	defer snapshotHTTP.stop()
	verificationCases := manifest.VerificationCases
	if len(verificationCases) == 0 {
		verificationCases = []domain.VerificationCase{{}}
	}
	for _, verification := range verificationCases {
		if err := verifyHelmCase(ctx, runner, image, snapshotHTTP, verification); err != nil {
			return buildgraph.RepositoryManifest{}, 0, err
		}
	}
	return manifest, len(manifest.VerificationCases), nil
}

// snapshotServer is a verified tree served to a client running in a container,
// plus how that container reaches it.
//
// There is no single mechanism that works everywhere. Where the runtime runs
// containers directly on the host — Linux, docker or podman — the container can
// share the host network namespace and read loopback, which keeps the socket
// unreachable from anywhere else. Where the runtime is a virtual machine, that
// namespace is the machine's rather than the host's, so the container instead
// resolves a mapped gateway alias and the socket has to accept it.
type snapshotServer struct {
	// endpoint is the URL as the container sees it.
	endpoint string
	// runnerArguments make the endpoint reachable from inside.
	runnerArguments []string
	stop            func()
}

const snapshotAlias = "snailmail-snapshot.invalid"

func serveSnapshot(snapshot string) (snapshotServer, error) {
	sharesHostNamespace := runtime.GOOS == "linux"
	address := ":0"
	if sharesHostNamespace {
		address = "127.0.0.1:0"
	}
	listener, err := net.Listen("tcp", address)
	if err != nil {
		return snapshotServer{}, fmt.Errorf("serve verification snapshot: %w", err)
	}
	_, port, err := net.SplitHostPort(listener.Addr().String())
	if err != nil {
		_ = listener.Close()
		return snapshotServer{}, err
	}
	server := &http.Server{Handler: http.FileServer(http.Dir(snapshot)), ReadHeaderTimeout: 10 * time.Second}
	go func() { _ = server.Serve(listener) }()

	result := snapshotServer{stop: func() {
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = server.Shutdown(shutdownCtx)
	}}
	if sharesHostNamespace {
		result.endpoint = "http://127.0.0.1:" + port
		result.runnerArguments = []string{"--network=host"}
		return result, nil
	}
	result.endpoint = "http://" + snapshotAlias + ":" + port
	result.runnerArguments = []string{"--add-host", snapshotAlias + ":host-gateway"}
	return result, nil
}

func verifyHelmCase(ctx context.Context, runner, image string, snapshotHTTP snapshotServer, verification domain.VerificationCase) error {
	caseCtx, cancel := context.WithTimeout(ctx, 3*time.Minute)
	defer cancel()
	arguments := []string{"run", "--rm", "--pull=missing"}
	arguments = append(arguments, snapshotHTTP.runnerArguments...)
	arguments = append(arguments,
		"--read-only", "--memory=768m", "--cpus=2", "--pids-limit=256",
		"--ulimit", "fsize=536870912:536870912", "--ulimit", "nofile=1024:1024",
		"--security-opt", "no-new-privileges",
		"--tmpfs", "/tmp:rw,exec,size=640m,mode=1777",
		"--tmpfs", "/home/helm:rw,size=32m,mode=0700",
		"--env", "HOME=/home/helm",
		"--env", "HELM_CACHE_HOME=/home/helm/cache",
		"--env", "HELM_CONFIG_HOME=/home/helm/config",
		"--env", "HELM_DATA_HOME=/home/helm/data",
		"--env", "SNAILMAIL_ENDPOINT="+snapshotHTTP.endpoint,
		"--env", "SNAILMAIL_CHART="+verification.Project,
		"--env", "SNAILMAIL_VERSION="+verification.Version,
		"--entrypoint", "/bin/sh",
		image,
		"-euc", `
helm repo add staged "$SNAILMAIL_ENDPOINT"
helm repo update staged
if test -n "$SNAILMAIL_CHART"; then
    mkdir -p /tmp/chart
    helm pull "staged/$SNAILMAIL_CHART" --version "$SNAILMAIL_VERSION" --untar --untardir /tmp/chart
    helm show chart "staged/$SNAILMAIL_CHART" --version "$SNAILMAIL_VERSION" >/tmp/chart-metadata.yaml
    helm lint "/tmp/chart/$SNAILMAIL_CHART"
    helm template snailmail "/tmp/chart/$SNAILMAIL_CHART" >/tmp/rendered.yaml
fi
`)
	command := exec.CommandContext(caseCtx, runner, arguments...)
	command.Env = runnerEnvironment()
	output, err := command.CombinedOutput()
	if err != nil {
		return fmt.Errorf("Helm client verification for %s@%s: %w\n%s", verification.Project, verification.Version, err, strings.TrimSpace(string(output)))
	}
	return nil
}

func validateManifestFile(file buildgraph.ManifestFile, index int, files []buildgraph.ManifestFile) error {
	if file.Path == "" || path.IsAbs(file.Path) || path.Clean(file.Path) != file.Path || file.Path == "." || strings.HasPrefix(file.Path, "../") || strings.ContainsRune(file.Path, '\\') {
		return fmt.Errorf("repository manifest contains unsafe path %q", file.Path)
	}
	if file.Path == buildgraph.ManifestFilename {
		return fmt.Errorf("repository manifest includes itself")
	}
	if index > 0 && files[index-1].Path >= file.Path {
		return errors.New("repository manifest file list is not uniquely sorted")
	}
	if file.Size < 0 {
		return fmt.Errorf("repository file %q has a negative size", file.Path)
	}
	decoded, err := hex.DecodeString(file.SHA256)
	if err != nil || len(decoded) != sha256.Size {
		return fmt.Errorf("repository file %q has an invalid SHA-256", file.Path)
	}
	return nil
}

func hashRepositoryFile(root, name string) (int64, string, error) {
	filename := filepath.Join(root, filepath.FromSlash(name))
	info, err := os.Lstat(filename)
	if err != nil {
		return 0, "", fmt.Errorf("inspect repository file %q: %w", name, err)
	}
	if !info.Mode().IsRegular() {
		return 0, "", fmt.Errorf("repository file %q is not a regular file", name)
	}
	file, err := os.Open(filename)
	if err != nil {
		return 0, "", fmt.Errorf("open repository file %q: %w", name, err)
	}
	hash := sha256.New()
	size, readErr := io.Copy(hash, file)
	closeErr := file.Close()
	if readErr != nil {
		return 0, "", fmt.Errorf("hash repository file %q: %w", name, readErr)
	}
	if closeErr != nil {
		return 0, "", fmt.Errorf("close repository file %q: %w", name, closeErr)
	}
	return size, hex.EncodeToString(hash.Sum(nil)), nil
}

func rejectUnexpectedFiles(root string, expected map[string]bool) error {
	var actual []string
	err := filepath.WalkDir(root, func(name string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.Type()&fs.ModeSymlink != 0 {
			return fmt.Errorf("repository contains symbolic link %q", name)
		}
		if entry.IsDir() {
			return nil
		}
		if !entry.Type().IsRegular() {
			return fmt.Errorf("repository contains non-regular file %q", name)
		}
		relative, err := filepath.Rel(root, name)
		if err != nil {
			return err
		}
		actual = append(actual, filepath.ToSlash(relative))
		return nil
	})
	if err != nil {
		return err
	}
	sort.Strings(actual)
	for _, name := range actual {
		if !expected[name] {
			return fmt.Errorf("repository contains unexpected file %q", name)
		}
		delete(expected, name)
	}
	if len(expected) != 0 {
		return errors.New("repository is missing files declared by its manifest")
	}
	return nil
}

func requireJSONEOF(decoder *json.Decoder) error {
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return errors.New("repository manifest contains more than one JSON value")
		}
		return fmt.Errorf("decode repository manifest: %w", err)
	}
	return nil
}

func verifyPyPIStructure(root string, manifest buildgraph.RepositoryManifest) ([]domain.Blob, error) {
	var blobs []domain.Blob
	for _, file := range manifest.Files {
		if file.Path == ".nojekyll" {
			if file.Size != 0 {
				return nil, errors.New("PyPI .nojekyll marker must be empty")
			}
			continue
		}
		// The browsable page is written for people, not for a client, and is
		// covered by the tree digest like everything else.
		if file.Path == listing.Filename {
			continue
		}
		if strings.HasPrefix(file.Path, "simple/") {
			if path.Base(file.Path) != "index.html" {
				return nil, fmt.Errorf("unexpected PyPI index path %q", file.Path)
			}
			continue
		}
		parts := strings.Split(file.Path, "/")
		if len(parts) != 3 || parts[0] != "packages" || parts[1] != file.SHA256 || !pypi.IsDistributionFilename(parts[2]) {
			return nil, fmt.Errorf("unexpected PyPI repository path %q", file.Path)
		}
		facts, cached := factscache.Lookup(pypi.FormatID, file.SHA256)
		if !cached {
			name := filepath.Join(root, filepath.FromSlash(file.Path))
			packageFile, err := os.Open(name)
			if err != nil {
				return nil, fmt.Errorf("open PyPI package %q: %w", file.Path, err)
			}
			var inspectErr error
			facts, inspectErr = pypi.Inspect(parts[2], packageFile, file.Size)
			closeErr := packageFile.Close()
			if inspectErr != nil {
				return nil, inspectErr
			}
			if closeErr != nil {
				return nil, fmt.Errorf("close PyPI package %q: %w", file.Path, closeErr)
			}
			factscache.Store(pypi.FormatID, file.SHA256, facts)
		}
		blobs = append(blobs, domain.Blob{Filename: parts[2], Size: file.Size, SHA256: file.SHA256, Facts: facts})
	}
	expectedArtifact, err := pypi.Build(blobs)
	if err != nil {
		return nil, fmt.Errorf("rebuild PyPI structure: %w", err)
	}
	generatedAt, err := time.Parse(time.RFC3339, manifest.GeneratedAt)
	if err != nil {
		return nil, err
	}
	_, expectedManifest, err := buildgraph.Finalize(expectedArtifact, generatedAt)
	if err != nil {
		return nil, fmt.Errorf("finalize expected PyPI structure: %w", err)
	}
	expectedManifest.SchemaVersion = manifest.SchemaVersion
	// The rebuild cannot reproduce the browsable page: it is written from the
	// repository name, endpoint and signing key, which do not survive into the
	// published tree. The tree digest still covers it.
	expectedManifest.Files = withoutListing(expectedManifest.Files)
	manifest.Files = withoutListing(manifest.Files)
	// The tree digest covers the page too, so it cannot match a rebuild that
	// omits it. What it protects is checked where it belongs: the deployment
	// record is matched against the digest of the tree that was published.
	expectedManifest.TreeSHA256, manifest.TreeSHA256 = "", ""
	if !reflect.DeepEqual(expectedManifest, manifest) {
		return nil, errors.New("PyPI indexes or verification metadata do not match package bytes")
	}
	return blobs, nil
}

func verifyDebStructure(root string, manifest buildgraph.RepositoryManifest) ([]domain.Blob, error) {
	var blobs []domain.Blob
	for _, file := range manifest.Files {
		// The browsable page is written for people, not for a client, and is
		// covered by the tree digest like everything else.
		if file.Path == listing.Filename {
			continue
		}
		if strings.HasPrefix(file.Path, "dists/") || (manifest.Install.SigningKeyPath != "" && file.Path == manifest.Install.SigningKeyPath) {
			continue
		}
		if !strings.HasPrefix(file.Path, "pool/") || !deb.IsPackageFilename(path.Base(file.Path)) {
			return nil, fmt.Errorf("unexpected Debian repository path %q", file.Path)
		}
		name := filepath.Join(root, filepath.FromSlash(file.Path))
		facts, cached := factscache.Lookup(deb.FormatID, file.SHA256)
		if !cached {
			packageFile, err := os.Open(name)
			if err != nil {
				return nil, fmt.Errorf("open Debian package %q: %w", file.Path, err)
			}
			var inspectErr error
			facts, inspectErr = deb.Inspect(path.Base(file.Path), packageFile, file.Size)
			closeErr := packageFile.Close()
			if inspectErr != nil {
				return nil, inspectErr
			}
			if closeErr != nil {
				return nil, fmt.Errorf("close Debian package %q: %w", file.Path, closeErr)
			}
			factscache.Store(deb.FormatID, file.SHA256, facts)
		}
		md5Value, sha1Value, err := legacyChecksums(name)
		if err != nil {
			return nil, err
		}
		blobs = append(blobs, domain.Blob{
			Filename: path.Base(file.Path),
			Size:     file.Size,
			MD5:      md5Value,
			SHA1:     sha1Value,
			SHA256:   file.SHA256,
			Facts:    facts,
		})
	}
	generatedAt, err := time.Parse(time.RFC3339, manifest.GeneratedAt)
	if err != nil {
		return nil, err
	}
	expectedArtifact, err := deb.Build(blobs, deb.BuildOptions{
		Suite:         manifest.Install.Suite,
		Component:     manifest.Install.Component,
		Architectures: manifest.Install.Architectures,
		GeneratedAt:   generatedAt,
	})
	if err != nil {
		return nil, fmt.Errorf("rebuild Debian structure: %w", err)
	}
	if manifest.Install.SigningKeyPath != "" {
		if len(manifest.Signatures) != 2 || manifest.Install.SigningFingerprint == "" || path.IsAbs(manifest.Install.SigningKeyPath) ||
			path.Clean(manifest.Install.SigningKeyPath) != manifest.Install.SigningKeyPath || !strings.HasPrefix(manifest.Install.SigningKeyPath, "keys/") {
			return nil, errors.New("signed Debian repository has incomplete signature metadata")
		}
		keyringContent, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(manifest.Install.SigningKeyPath)))
		if err != nil {
			return nil, fmt.Errorf("read Debian public signing key: %w", err)
		}
		inRelease, err := os.ReadFile(filepath.Join(root, "dists", manifest.Install.Suite, "InRelease"))
		if err != nil {
			return nil, fmt.Errorf("read Debian InRelease: %w", err)
		}
		releaseGPG, err := os.ReadFile(filepath.Join(root, "dists", manifest.Install.Suite, "Release.gpg"))
		if err != nil {
			return nil, fmt.Errorf("read Debian Release.gpg: %w", err)
		}
		signatureTime, err := time.Parse(time.RFC3339, manifest.Signatures[0].CreatedAt)
		if err != nil || manifest.Signatures[1].CreatedAt != manifest.Signatures[0].CreatedAt {
			return nil, errors.New("Debian signature metadata has inconsistent creation times")
		}
		trustedFingerprints := append([]string(nil), manifest.Install.TrustedSigningFingerprints...)
		if len(trustedFingerprints) == 0 {
			trustedFingerprints = []string{manifest.Install.SigningFingerprint}
		}
		activePublic, err := openpgpsigner.ExtractPublicKey(keyringContent, manifest.Install.SigningFingerprint)
		if err != nil {
			return nil, fmt.Errorf("extract active Debian signing key: %w", err)
		}
		expectedArtifact, err = deb.ApplySigning(expectedArtifact, manifest.Install.Suite, deb.SigningMaterial{
			Fingerprint: manifest.Install.SigningFingerprint, PublicKey: activePublic,
			KeyringPath: manifest.Install.SigningKeyPath, PublicKeyring: keyringContent, TrustedFingerprints: trustedFingerprints,
			SignatureTime: signatureTime, InRelease: inRelease, ReleaseGPG: releaseGPG,
		})
		if err != nil {
			return nil, fmt.Errorf("verify Debian signatures: %w", err)
		}
	} else if len(manifest.Signatures) != 0 {
		return nil, errors.New("unsigned Debian repository contains signature metadata")
	}
	_, expectedManifest, err := buildgraph.Finalize(expectedArtifact, generatedAt)
	if err != nil {
		return nil, fmt.Errorf("finalize expected Debian structure: %w", err)
	}
	expectedManifest.SchemaVersion = manifest.SchemaVersion
	if manifest.SchemaVersion < 3 {
		expectedManifest.Install.TrustedSigningFingerprints = nil
	}
	// The rebuild cannot reproduce the browsable page: it is written from the
	// repository name, endpoint and signing key, which do not survive into the
	// published tree. The tree digest still covers it.
	expectedManifest.Files = withoutListing(expectedManifest.Files)
	manifest.Files = withoutListing(manifest.Files)
	// The tree digest covers the page too, so it cannot match a rebuild that
	// omits it. What it protects is checked where it belongs: the deployment
	// record is matched against the digest of the tree that was published.
	expectedManifest.TreeSHA256, manifest.TreeSHA256 = "", ""
	if !reflect.DeepEqual(expectedManifest, manifest) {
		return nil, errors.New("Debian indexes or verification metadata do not match package bytes")
	}
	return blobs, nil
}

func verifyHelmStructure(root string, manifest buildgraph.RepositoryManifest) ([]domain.Blob, error) {
	var blobs []domain.Blob
	for _, file := range manifest.Files {
		// The browsable page is written for people, not for a client, and is
		// covered by the tree digest like everything else.
		if file.Path == listing.Filename {
			continue
		}
		if file.Path == "index.yaml" {
			continue
		}
		// Signing material is checked below by rebuilding it, the same way the
		// Debian path does: the published key and each chart's provenance are
		// re-applied to the rebuilt tree, which verifies every signature.
		if strings.HasPrefix(file.Path, "keys/") || strings.HasSuffix(file.Path, helm.ProvenanceSuffix) {
			continue
		}
		parts := strings.Split(file.Path, "/")
		if len(parts) != 3 || parts[0] != "charts" || parts[1] != file.SHA256 || !helm.IsChartFilename(parts[2]) {
			return nil, fmt.Errorf("unexpected Helm repository path %q", file.Path)
		}
		facts, cached := factscache.Lookup(helm.FormatID, file.SHA256)
		if !cached {
			name := filepath.Join(root, filepath.FromSlash(file.Path))
			chartFile, err := os.Open(name)
			if err != nil {
				return nil, fmt.Errorf("open Helm chart %q: %w", file.Path, err)
			}
			var inspectErr error
			facts, inspectErr = helm.Inspect(parts[2], chartFile, file.Size)
			closeErr := chartFile.Close()
			if inspectErr != nil {
				return nil, inspectErr
			}
			if closeErr != nil {
				return nil, fmt.Errorf("close Helm chart %q: %w", file.Path, closeErr)
			}
			factscache.Store(helm.FormatID, file.SHA256, facts)
		}
		blobs = append(blobs, domain.Blob{Filename: parts[2], Size: file.Size, SHA256: file.SHA256, Facts: facts})
	}
	generatedAt, err := time.Parse(time.RFC3339, manifest.GeneratedAt)
	if err != nil {
		return nil, err
	}
	expectedArtifact, err := helm.Build(blobs, helm.BuildOptions{GeneratedAt: generatedAt})
	if err != nil {
		return nil, fmt.Errorf("rebuild Helm structure: %w", err)
	}
	if manifest.Install.SigningKeyPath != "" {
		if len(manifest.Signatures) == 0 || manifest.Install.SigningFingerprint == "" || path.IsAbs(manifest.Install.SigningKeyPath) ||
			path.Clean(manifest.Install.SigningKeyPath) != manifest.Install.SigningKeyPath || !strings.HasPrefix(manifest.Install.SigningKeyPath, "keys/") {
			return nil, errors.New("signed Helm repository has incomplete signature metadata")
		}
		keyring, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(manifest.Install.SigningKeyPath)))
		if err != nil {
			return nil, fmt.Errorf("read Helm public signing key: %w", err)
		}
		provenance := make(map[string][]byte, len(manifest.Signatures))
		signatureTime, err := time.Parse(time.RFC3339, manifest.Signatures[0].CreatedAt)
		if err != nil {
			return nil, errors.New("Helm signature metadata has an invalid creation time")
		}
		for _, signature := range manifest.Signatures {
			if signature.CreatedAt != manifest.Signatures[0].CreatedAt {
				return nil, errors.New("Helm signature metadata has inconsistent creation times")
			}
			if !strings.HasSuffix(signature.Path, helm.ProvenanceSuffix) {
				return nil, fmt.Errorf("Helm signature at %q is not a provenance file", signature.Path)
			}
			content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(signature.Path)))
			if err != nil {
				return nil, fmt.Errorf("read Helm provenance %q: %w", signature.Path, err)
			}
			provenance[strings.TrimSuffix(signature.Path, helm.ProvenanceSuffix)] = content
		}
		activePublic, err := openpgpsigner.ExtractPublicKey(keyring, manifest.Install.SigningFingerprint)
		if err != nil {
			return nil, fmt.Errorf("extract active Helm signing key: %w", err)
		}
		expectedArtifact, err = helm.ApplySigning(expectedArtifact, helm.SigningMaterial{
			Fingerprint: manifest.Install.SigningFingerprint, PublicKey: activePublic,
			PublicKeyring: keyring, KeyringPath: manifest.Install.SigningKeyPath,
			SignatureTime: signatureTime, Provenance: provenance,
		})
		if err != nil {
			return nil, fmt.Errorf("verify Helm signatures: %w", err)
		}
	} else if len(manifest.Signatures) != 0 {
		return nil, errors.New("unsigned Helm repository contains signature metadata")
	}
	_, expectedManifest, err := buildgraph.Finalize(expectedArtifact, generatedAt)
	if err != nil {
		return nil, fmt.Errorf("finalize expected Helm structure: %w", err)
	}
	expectedManifest.SchemaVersion = manifest.SchemaVersion
	// The rebuild cannot reproduce the browsable page: it is written from the
	// repository name, endpoint and signing key, which do not survive into the
	// published tree. The tree digest still covers it.
	expectedManifest.Files = withoutListing(expectedManifest.Files)
	manifest.Files = withoutListing(manifest.Files)
	// The tree digest covers the page too, so it cannot match a rebuild that
	// omits it. What it protects is checked where it belongs: the deployment
	// record is matched against the digest of the tree that was published.
	expectedManifest.TreeSHA256, manifest.TreeSHA256 = "", ""
	if !reflect.DeepEqual(expectedManifest, manifest) {
		return nil, errors.New("Helm index or verification metadata does not match chart bytes")
	}
	return blobs, nil
}

func legacyChecksums(name string) (string, string, error) {
	file, err := os.Open(name)
	if err != nil {
		return "", "", err
	}
	md5Hash := md5.New()
	sha1Hash := sha1.New()
	_, readErr := io.Copy(io.MultiWriter(md5Hash, sha1Hash), file)
	closeErr := file.Close()
	if readErr != nil {
		return "", "", readErr
	}
	if closeErr != nil {
		return "", "", closeErr
	}
	return hex.EncodeToString(md5Hash.Sum(nil)), hex.EncodeToString(sha1Hash.Sum(nil)), nil
}

func snapshotRepository(ctx context.Context, source string, manifest buildgraph.RepositoryManifest) (string, error) {
	snapshot, err := os.MkdirTemp("", ".snailmail-repository-*")
	if err != nil {
		return "", fmt.Errorf("create repository snapshot: %w", err)
	}
	if err := os.Chmod(snapshot, 0o755); err != nil {
		_ = os.RemoveAll(snapshot)
		return "", fmt.Errorf("make repository snapshot readable: %w", err)
	}
	keep := false
	defer func() {
		if !keep {
			_ = os.RemoveAll(snapshot)
		}
	}()
	files := make([]buildgraph.ManifestFile, 0, len(manifest.Files)+1)
	files = append(files, manifest.Files...)
	manifestInfo, err := os.Lstat(filepath.Join(source, buildgraph.ManifestFilename))
	if err != nil {
		return "", err
	}
	if !manifestInfo.Mode().IsRegular() || manifestInfo.Size() > maxManifestSize {
		return "", errors.New("repository manifest is not a bounded regular file")
	}
	files = append(files, buildgraph.ManifestFile{Path: buildgraph.ManifestFilename, Size: manifestInfo.Size()})
	for _, file := range files {
		if err := ctx.Err(); err != nil {
			return "", err
		}
		name := filepath.Join(source, filepath.FromSlash(file.Path))
		info, err := os.Lstat(name)
		if err != nil {
			return "", err
		}
		if !info.Mode().IsRegular() || info.Size() != file.Size {
			return "", fmt.Errorf("repository file %q changed before snapshot", file.Path)
		}
		target := filepath.Join(snapshot, filepath.FromSlash(file.Path))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return "", err
		}
		if err := linkOrCopyFile(name, target, file.Size); err != nil {
			return "", err
		}
	}
	keep = true
	return snapshot, nil
}

// linkOrCopyFile prefers a hard link, so snapshotting a repository that can
// reach the 4 GiB verification limit does not duplicate every byte. The link
// shares the inode with an immutable release file, and the snapshot is only
// ever read, so the two stay identical by construction. A link across
// filesystems, or onto one that does not support them, falls back to copying.
func linkOrCopyFile(sourceName, targetName string, expectedSize int64) error {
	if err := os.Link(sourceName, targetName); err == nil {
		info, statErr := os.Lstat(targetName)
		if statErr != nil {
			return statErr
		}
		if !info.Mode().IsRegular() || info.Size() != expectedSize {
			return fmt.Errorf("repository file %q changed while snapshotting", sourceName)
		}
		return nil
	}
	return copyFile(sourceName, targetName, expectedSize)
}

func copyFile(sourceName, targetName string, expectedSize int64) error {
	source, err := os.Open(sourceName)
	if err != nil {
		return err
	}
	destination, err := os.OpenFile(targetName, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		_ = source.Close()
		return err
	}
	written, copyErr := io.Copy(destination, io.LimitReader(source, expectedSize+1))
	closeDestinationErr := destination.Close()
	closeSourceErr := source.Close()
	if copyErr != nil {
		return copyErr
	}
	if written != expectedSize {
		return fmt.Errorf("repository file %q changed while snapshotting", sourceName)
	}
	if closeDestinationErr != nil {
		return closeDestinationErr
	}
	return closeSourceErr
}

// verifyRawStructure recomputes a raw repository from its published tree.
//
// Identity is read from the path rather than the filename, which is what makes
// an operator-supplied name verifiable after publication: the build put it
// there, so re-deriving it needs no access to the flags used at ingest.
func verifyRawStructure(root string, manifest buildgraph.RepositoryManifest) ([]domain.Blob, error) {
	var blobs []domain.Blob
	for _, file := range manifest.Files {
		if file.Path == "SHA256SUMS" || file.Path == "index.html" {
			continue
		}
		parts := strings.Split(file.Path, "/")
		if len(parts) != 3 {
			return nil, fmt.Errorf("unexpected raw repository path %q", file.Path)
		}
		name, version, filename := parts[0], parts[1], parts[2]
		if !raw.IsArtifactFilename(filename) {
			return nil, fmt.Errorf("unexpected raw artifact filename %q", file.Path)
		}
		facts, err := raw.FactsFor(name, version, filename)
		if err != nil {
			return nil, fmt.Errorf("raw artifact %q: %w", file.Path, err)
		}
		blobs = append(blobs, domain.Blob{Filename: filename, Size: file.Size, SHA256: file.SHA256, Facts: facts})
	}
	generatedAt, err := time.Parse(time.RFC3339, manifest.GeneratedAt)
	if err != nil {
		return nil, err
	}
	expectedArtifact, err := raw.Build(blobs, raw.BuildOptions{GeneratedAt: generatedAt})
	if err != nil {
		return nil, fmt.Errorf("rebuild raw structure: %w", err)
	}
	_, expectedManifest, err := buildgraph.Finalize(expectedArtifact, generatedAt)
	if err != nil {
		return nil, fmt.Errorf("finalize expected raw structure: %w", err)
	}
	// The browsable page is left out of the comparison. It is written from the
	// repository's name, endpoint and signing key, none of which survive into
	// the published tree, so it cannot be recomputed from what is there. What
	// this check exists for is the machine-readable side: that every artifact is
	// where the checksums say and nothing else is present. The page is still
	// covered by the tree digest, which the deployment record is matched
	// against, so altering it does not go unnoticed.
	if !reflect.DeepEqual(withoutListing(expectedManifest.Files), withoutListing(manifest.Files)) {
		return nil, errors.New("raw checksums do not match the published artifacts")
	}
	return blobs, nil
}

// VerifyRawClientEndpointAccess proves a host serves exactly the raw tree that
// was reviewed.
//
// There is no client to run: a raw consumer fetches a URL and checks it against
// SHA256SUMS. Fetching every route and comparing digests is that check, done
// against the host rather than trusting it.
func VerifyRawClientEndpointAccess(ctx context.Context, root string, access host.ClientAccess) (buildgraph.RepositoryManifest, int, error) {
	if access.Credential != nil {
		defer access.Credential.Destroy()
	}
	if _, err := validateClientEndpoint(access.Endpoint); err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	manifest, _, err := verifyRepository(root)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	if manifest.Format != raw.FormatID {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("repository format is %q, not %q", manifest.Format, raw.FormatID)
	}
	if len(access.Routes) == 0 {
		access.Routes, err = defaultClientRoutes(access.Endpoint, manifest.Files)
		if err != nil {
			return buildgraph.RepositoryManifest{}, 0, err
		}
	}
	if err := awaitHostedBytes(ctx, access, "", "", false); err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	return manifest, len(manifest.VerificationCases), nil
}

// withoutListing drops the human-readable page from a file set, leaving what a
// client reads.
func withoutListing(files []buildgraph.ManifestFile) []buildgraph.ManifestFile {
	kept := make([]buildgraph.ManifestFile, 0, len(files))
	for _, file := range files {
		if file.Path == listing.Filename {
			continue
		}
		kept = append(kept, file)
	}
	return kept
}
