package app

import (
	"context"
	"crypto/md5"
	"crypto/sha1"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/shellcell/snailmail/formats/deb"
	"github.com/shellcell/snailmail/formats/helm"
	"github.com/shellcell/snailmail/formats/pypi"
	"github.com/shellcell/snailmail/internal/buildgraph"
	"github.com/shellcell/snailmail/internal/domain"
)

const (
	maxManifestSize    = 8 << 20
	maxRepositoryFiles = 20_000
	maxRepositoryBytes = 4 << 30
)

// VerifyRepository checks the management manifest and every generated byte.
func VerifyRepository(root string) (buildgraph.RepositoryManifest, error) {
	manifest, _, err := verifyRepository(root)
	return manifest, err
}

func verifyRepository(root string) (buildgraph.RepositoryManifest, []domain.Blob, error) {
	absolute, err := filepath.Abs(root)
	if err != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("resolve repository: %w", err)
	}
	absolute, err = filepath.EvalSymlinks(absolute)
	if err != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("resolve repository release: %w", err)
	}
	manifestPath := filepath.Join(absolute, buildgraph.ManifestFilename)
	manifestFile, err := os.Open(manifestPath)
	if err != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("open repository manifest: %w", err)
	}
	manifestBytes, readErr := io.ReadAll(io.LimitReader(manifestFile, maxManifestSize+1))
	closeErr := manifestFile.Close()
	if readErr != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("read repository manifest: %w", readErr)
	}
	if closeErr != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("close repository manifest: %w", closeErr)
	}
	if len(manifestBytes) > maxManifestSize {
		return buildgraph.RepositoryManifest{}, nil, errors.New("repository manifest exceeds 8 MiB")
	}
	decoder := json.NewDecoder(strings.NewReader(string(manifestBytes)))
	decoder.DisallowUnknownFields()
	var manifest buildgraph.RepositoryManifest
	if err := decoder.Decode(&manifest); err != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("decode repository manifest: %w", err)
	}
	if err := requireJSONEOF(decoder); err != nil {
		return buildgraph.RepositoryManifest{}, nil, err
	}
	if manifest.SchemaVersion != buildgraph.ManifestSchema {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("unsupported repository schema %d", manifest.SchemaVersion)
	}
	if manifest.Format == "" {
		return buildgraph.RepositoryManifest{}, nil, errors.New("repository manifest has no format")
	}
	if _, err := time.Parse(time.RFC3339, manifest.GeneratedAt); err != nil {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("invalid generation time: %w", err)
	}
	if len(manifest.Files) > maxRepositoryFiles {
		return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("repository has more than %d files", maxRepositoryFiles)
	}
	var repositorySize int64
	for _, file := range manifest.Files {
		if file.Size < 0 || file.Size > maxRepositoryBytes-repositorySize {
			return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("repository exceeds the %d byte verification limit", maxRepositoryBytes)
		}
		repositorySize += file.Size
	}

	expected := map[string]bool{buildgraph.ManifestFilename: true}
	for index, file := range manifest.Files {
		if err := validateManifestFile(file, index, manifest.Files); err != nil {
			return buildgraph.RepositoryManifest{}, nil, err
		}
		expected[file.Path] = true
		actualSize, actualHash, err := hashRepositoryFile(absolute, file.Path)
		if err != nil {
			return buildgraph.RepositoryManifest{}, nil, err
		}
		if actualSize != file.Size || actualHash != file.SHA256 {
			return buildgraph.RepositoryManifest{}, nil, fmt.Errorf("repository file %q does not match its manifest", file.Path)
		}
	}
	if buildgraph.TreeDigest(manifest.Files) != manifest.TreeSHA256 {
		return buildgraph.RepositoryManifest{}, nil, errors.New("repository tree digest does not match its manifest")
	}
	if err := rejectUnexpectedFiles(absolute, expected); err != nil {
		return buildgraph.RepositoryManifest{}, nil, err
	}
	var blobs []domain.Blob
	if manifest.Format == pypi.FormatID {
		blobs, err = verifyPyPIStructure(absolute, manifest)
		if err != nil {
			return buildgraph.RepositoryManifest{}, nil, err
		}
	}
	if manifest.Format == deb.FormatID {
		blobs, err = verifyDebStructure(absolute, manifest)
		if err != nil {
			return buildgraph.RepositoryManifest{}, nil, err
		}
	}
	if manifest.Format == helm.FormatID {
		blobs, err = verifyHelmStructure(absolute, manifest)
		if err != nil {
			return buildgraph.RepositoryManifest{}, nil, err
		}
	}
	return manifest, blobs, nil
}

// VerifyPyPIClient installs every unique project version with pip from an
// ephemeral HTTP server over the verified tree.
func VerifyPyPIClient(ctx context.Context, root, python string) (buildgraph.RepositoryManifest, int, error) {
	release, err := filepath.Abs(root)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository: %w", err)
	}
	release, err = filepath.EvalSymlinks(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository release: %w", err)
	}
	manifest, _, err := verifyRepository(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	snapshot, err := snapshotRepository(ctx, release, manifest)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	defer os.RemoveAll(snapshot)
	manifest, blobs, err := verifyRepository(snapshot)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	if manifest.Format != pypi.FormatID {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("repository format is %q, not %q", manifest.Format, pypi.FormatID)
	}
	if python == "" {
		python = "python3"
	}
	python, err = exec.LookPath(python)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("find Python client: %w", err)
	}
	wheels := make(map[string]bool)
	for _, blob := range blobs {
		if strings.HasSuffix(strings.ToLower(blob.Filename), ".whl") {
			wheels[pypi.NormalizeName(blob.Facts.Name)+"\x00"+blob.Facts.Version] = true
		}
		for _, requirement := range blob.Facts.Requirements {
			if strings.Contains(requirement, "@") {
				return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("host verification rejects direct URL requirement %q; use an isolated runner", requirement)
			}
		}
	}
	for _, verification := range manifest.VerificationCases {
		if !wheels[verification.Project+"\x00"+verification.Version] {
			return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("%s==%s has no wheel; source distribution verification requires an isolated runner", verification.Project, verification.Version)
		}
	}

	server := httptest.NewServer(http.FileServer(http.Dir(snapshot)))
	defer server.Close()

	for _, verification := range manifest.VerificationCases {
		sandbox, err := os.MkdirTemp("", ".snailmail-pip-*")
		if err != nil {
			return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("create pip sandbox: %w", err)
		}
		target := filepath.Join(sandbox, "target")
		home := filepath.Join(sandbox, "home")
		temporary := filepath.Join(sandbox, "tmp")
		if err := os.MkdirAll(home, 0o700); err != nil {
			_ = os.RemoveAll(sandbox)
			return buildgraph.RepositoryManifest{}, 0, err
		}
		if err := os.MkdirAll(temporary, 0o700); err != nil {
			_ = os.RemoveAll(sandbox)
			return buildgraph.RepositoryManifest{}, 0, err
		}
		arguments := []string{
			"-I", "-m", "pip", "install",
			"--disable-pip-version-check",
			"--no-input",
			"--no-build-isolation",
			"--only-binary=:all:",
			"--no-compile",
			"--index-url", server.URL + "/" + manifest.Install.IndexPath,
			"--target", target,
			"--", verification.Project + "==" + verification.Version,
		}
		command := exec.CommandContext(ctx, python, arguments...)
		command.Dir = sandbox
		command.Env = []string{
			"HOME=" + home,
			"TMPDIR=" + temporary,
			"PATH=" + os.Getenv("PATH"),
			"LANG=C.UTF-8",
			"PIP_CONFIG_FILE=" + os.DevNull,
			"PIP_NO_CACHE_DIR=1",
			"PYTHONNOUSERSITE=1",
			"HTTP_PROXY=http://127.0.0.1:9",
			"HTTPS_PROXY=http://127.0.0.1:9",
			"http_proxy=http://127.0.0.1:9",
			"https_proxy=http://127.0.0.1:9",
			"NO_PROXY=127.0.0.1,localhost",
			"no_proxy=127.0.0.1,localhost",
		}
		output, commandErr := command.CombinedOutput()
		removeErr := os.RemoveAll(sandbox)
		if commandErr != nil {
			return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("pip install %s==%s: %w\n%s", verification.Project, verification.Version, commandErr, strings.TrimSpace(string(output)))
		}
		if removeErr != nil {
			return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("remove pip target: %w", removeErr)
		}
	}
	return manifest, len(manifest.VerificationCases), nil
}

// VerifyDebClient resolves and extracts each planned package version in its own
// bounded, network-isolated Debian container.
func VerifyDebClient(ctx context.Context, root, runner, image string, maxWorkspaceBytes int64) (buildgraph.RepositoryManifest, int, error) {
	release, err := filepath.Abs(root)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository: %w", err)
	}
	release, err = filepath.EvalSymlinks(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository release: %w", err)
	}
	manifest, _, err := verifyRepository(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	snapshot, err := snapshotRepository(ctx, release, manifest)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	defer os.RemoveAll(snapshot)
	manifest, blobs, err := verifyRepository(snapshot)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	if manifest.Format != deb.FormatID {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("repository format is %q, not %q", manifest.Format, deb.FormatID)
	}
	if runner == "" {
		runner = "podman"
	}
	runner, err = exec.LookPath(runner)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("find container runner: %w", err)
	}
	if !digestPinnedImage(image) {
		return buildgraph.RepositoryManifest{}, 0, errors.New("a digest-pinned Debian verification image is required")
	}
	workspaceBytes, err := debWorkspaceSize(blobs, maxWorkspaceBytes)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	for _, verification := range manifest.VerificationCases {
		if err := verifyDebCase(ctx, runner, image, snapshot, workspaceBytes, manifest, verification); err != nil {
			return buildgraph.RepositoryManifest{}, 0, err
		}
	}
	return manifest, len(manifest.VerificationCases), nil
}

func verifyDebCase(ctx context.Context, runner, image, snapshot string, workspaceBytes int64, manifest buildgraph.RepositoryManifest, verification domain.VerificationCase) error {
	platform, err := debOCIPlatform(verification.Architecture)
	if err != nil {
		return err
	}
	caseCtx, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()
	memoryBytes := workspaceBytes + 512<<20
	arguments := []string{
		"run", "--rm", "--pull=missing", "--network=none",
		"--platform", platform,
		"--read-only", "--memory=" + strconv.FormatInt(memoryBytes, 10), "--cpus=2", "--pids-limit=256",
		"--ulimit", "fsize=536870912:536870912", "--ulimit", "nofile=1024:1024",
		"--security-opt", "no-new-privileges",
		"--volume", snapshot + ":/target/repo:ro,Z",
		"--env", "DEBIAN_FRONTEND=noninteractive",
		"--env", "SNAILMAIL_SUITE=" + manifest.Install.Suite,
		"--env", "SNAILMAIL_COMPONENT=" + manifest.Install.Component,
		"--env", "SNAILMAIL_ARCHITECTURE=" + verification.Architecture,
		"--env", "SNAILMAIL_PACKAGE=" + verification.Package,
		"--env", "SNAILMAIL_VERSION=" + verification.Version,
		"--tmpfs", "/tmp:rw,size=64m,mode=1777",
		"--tmpfs", "/target:rw,size=" + strconv.FormatInt(workspaceBytes, 10) + ",mode=0755",
		image,
		"sh", "-euc", `
for directory in bin etc lib lib64 sbin usr var; do
    test -e "/$directory" && cp -a "/$directory" /target/
done
mkdir -p /target/dev /target/proc /target/sys /target/tmp
chmod 1777 /target/tmp
: >/target/dev/null
rm -rf /target/etc/apt/sources.list.d/* /target/etc/apt/sources.list
mkdir -p /target/var/lib/apt/lists/partial /target/var/cache/apt/archives/partial
printf 'deb [trusted=yes arch=%s] file:/repo %s %s\n' "$SNAILMAIL_ARCHITECTURE" "$SNAILMAIL_SUITE" "$SNAILMAIL_COMPONENT" >/target/etc/apt/sources.list
chroot /target apt-get -o APT::Sandbox::User=root -o Acquire::Languages=none update
chroot /target apt-get -o APT::Sandbox::User=root install -y --reinstall --no-install-recommends "$SNAILMAIL_PACKAGE=$SNAILMAIL_VERSION"
status=$(chroot /target dpkg-query -W -f='${Status} ${Version}' "$SNAILMAIL_PACKAGE")
test "$status" = "install ok installed $SNAILMAIL_VERSION"
`,
	}
	command := exec.CommandContext(caseCtx, runner, arguments...)
	command.Env = os.Environ()
	output, err := command.CombinedOutput()
	if err != nil {
		return fmt.Errorf("Debian client verification for %s=%s/%s: %w\n%s", verification.Package, verification.Version, verification.Architecture, err, strings.TrimSpace(string(output)))
	}
	return nil
}

func debWorkspaceSize(blobs []domain.Blob, maximum int64) (int64, error) {
	const (
		baseRootBytes = 256 << 20
		minimumBytes  = 768 << 20
	)
	if maximum <= 0 {
		return 0, errors.New("Debian verification workspace limit must be positive")
	}
	required := int64(baseRootBytes)
	for _, blob := range blobs {
		addition := blob.Size + blob.Facts.InstalledSize
		if addition < 0 || required > maximum-addition {
			return 0, fmt.Errorf("Debian verification requires more than the configured %d byte workspace", maximum)
		}
		required += addition
	}
	if required < minimumBytes {
		required = minimumBytes
	}
	if required > maximum {
		return 0, fmt.Errorf("Debian verification requires %d bytes, above the configured %d byte workspace", required, maximum)
	}
	return required, nil
}

func digestPinnedImage(image string) bool {
	digest := ""
	if separator := strings.LastIndex(image, "@sha256:"); separator >= 0 {
		digest = image[separator+len("@sha256:"):]
	} else if strings.HasPrefix(image, "sha256:") {
		digest = strings.TrimPrefix(image, "sha256:")
	}
	if len(digest) != sha256.Size*2 || digest != strings.ToLower(digest) {
		return false
	}
	decoded, err := hex.DecodeString(digest)
	return err == nil && len(decoded) == sha256.Size
}

func debOCIPlatform(architecture string) (string, error) {
	platforms := map[string]string{
		"amd64":    "linux/amd64",
		"arm64":    "linux/arm64",
		"armhf":    "linux/arm/v7",
		"armel":    "linux/arm/v5",
		"i386":     "linux/386",
		"mips64el": "linux/mips64le",
		"ppc64el":  "linux/ppc64le",
		"s390x":    "linux/s390x",
	}
	platform := platforms[architecture]
	if platform == "" {
		return "", fmt.Errorf("no OCI platform mapping for Debian architecture %q", architecture)
	}
	return platform, nil
}

func VerifyHelmClient(ctx context.Context, root, runner, image string) (buildgraph.RepositoryManifest, int, error) {
	release, err := filepath.Abs(root)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository: %w", err)
	}
	release, err = filepath.EvalSymlinks(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("resolve repository release: %w", err)
	}
	manifest, _, err := verifyRepository(release)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	snapshot, err := snapshotRepository(ctx, release, manifest)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	defer os.RemoveAll(snapshot)
	manifest, _, err = verifyRepository(snapshot)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, err
	}
	if manifest.Format != helm.FormatID {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("repository format is %q, not %q", manifest.Format, helm.FormatID)
	}
	if runner == "" {
		runner = "podman"
	}
	runner, err = exec.LookPath(runner)
	if err != nil {
		return buildgraph.RepositoryManifest{}, 0, fmt.Errorf("find container runner: %w", err)
	}
	if !digestPinnedImage(image) {
		return buildgraph.RepositoryManifest{}, 0, errors.New("a digest-pinned Helm verification image is required")
	}
	for _, verification := range manifest.VerificationCases {
		if err := verifyHelmCase(ctx, runner, image, snapshot, verification); err != nil {
			return buildgraph.RepositoryManifest{}, 0, err
		}
	}
	return manifest, len(manifest.VerificationCases), nil
}

func verifyHelmCase(ctx context.Context, runner, image, snapshot string, verification domain.VerificationCase) error {
	caseCtx, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()
	arguments := []string{
		"run", "--rm", "--pull=missing", "--network=none",
		"--read-only", "--memory=768m", "--cpus=2", "--pids-limit=256",
		"--ulimit", "fsize=536870912:536870912", "--ulimit", "nofile=1024:1024",
		"--security-opt", "no-new-privileges",
		"--volume", snapshot + ":/repo:ro,Z",
		"--tmpfs", "/tmp:rw,size=640m,mode=1777",
		"--tmpfs", "/home/helm:rw,size=32m,mode=0700",
		"--env", "HOME=/home/helm",
		"--env", "HELM_CACHE_HOME=/home/helm/cache",
		"--env", "HELM_CONFIG_HOME=/home/helm/config",
		"--env", "HELM_DATA_HOME=/home/helm/data",
		"--env", "SNAILMAIL_CHART=" + verification.Project,
		"--env", "SNAILMAIL_VERSION=" + verification.Version,
		"--entrypoint", "/bin/sh",
		image,
		"-euc", `
cat >/tmp/http-handler <<'HANDLER'
#!/bin/sh
IFS=' ' read -r method target protocol
carriage_return=$(printf '\r')
while IFS= read -r header; do
    test "$header" = "$carriage_return" && break
done
target=${target%%\?*}
case "$target" in
    /*) ;;
    *) target=/invalid ;;
esac
case "$target" in
    *..*) target=/invalid ;;
esac
file="/repo$target"
if test -f "$file"; then
    size=$(wc -c <"$file")
    type=application/octet-stream
    case "$file" in
        *.yaml) type=application/x-yaml ;;
        *.tgz) type=application/gzip ;;
    esac
    printf 'HTTP/1.1 200 OK\r\nContent-Length: %s\r\nContent-Type: %s\r\nConnection: close\r\n\r\n' "$size" "$type"
    cat "$file"
else
    printf 'HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n'
fi
HANDLER
chmod 0700 /tmp/http-handler
nc -lk -s 127.0.0.1 -p 8879 -e /tmp/http-handler &
server=$!
trap 'kill "$server"' EXIT
helm repo add staged http://127.0.0.1:8879
helm repo update staged
mkdir -p /tmp/chart
helm pull "staged/$SNAILMAIL_CHART" --version "$SNAILMAIL_VERSION" --untar --untardir /tmp/chart
helm show chart "staged/$SNAILMAIL_CHART" --version "$SNAILMAIL_VERSION" >/tmp/chart-metadata.yaml
helm lint "/tmp/chart/$SNAILMAIL_CHART"
helm template snailmail "/tmp/chart/$SNAILMAIL_CHART" >/tmp/rendered.yaml
`,
	}
	command := exec.CommandContext(caseCtx, runner, arguments...)
	command.Env = os.Environ()
	output, err := command.CombinedOutput()
	if err != nil {
		return fmt.Errorf("Helm client verification for %s@%s: %w\n%s", verification.Project, verification.Version, err, strings.TrimSpace(string(output)))
	}
	return nil
}

func validateManifestFile(file buildgraph.ManifestFile, index int, files []buildgraph.ManifestFile) error {
	if file.Path == "" || path.IsAbs(file.Path) || path.Clean(file.Path) != file.Path || file.Path == "." || strings.HasPrefix(file.Path, "../") || strings.ContainsRune(file.Path, '\\') {
		return fmt.Errorf("repository manifest contains unsafe path %q", file.Path)
	}
	if file.Path == buildgraph.ManifestFilename {
		return fmt.Errorf("repository manifest includes itself")
	}
	if index > 0 && files[index-1].Path >= file.Path {
		return errors.New("repository manifest file list is not uniquely sorted")
	}
	if file.Size < 0 {
		return fmt.Errorf("repository file %q has a negative size", file.Path)
	}
	decoded, err := hex.DecodeString(file.SHA256)
	if err != nil || len(decoded) != sha256.Size {
		return fmt.Errorf("repository file %q has an invalid SHA-256", file.Path)
	}
	return nil
}

func hashRepositoryFile(root, name string) (int64, string, error) {
	filename := filepath.Join(root, filepath.FromSlash(name))
	info, err := os.Lstat(filename)
	if err != nil {
		return 0, "", fmt.Errorf("inspect repository file %q: %w", name, err)
	}
	if !info.Mode().IsRegular() {
		return 0, "", fmt.Errorf("repository file %q is not a regular file", name)
	}
	file, err := os.Open(filename)
	if err != nil {
		return 0, "", fmt.Errorf("open repository file %q: %w", name, err)
	}
	hash := sha256.New()
	size, readErr := io.Copy(hash, file)
	closeErr := file.Close()
	if readErr != nil {
		return 0, "", fmt.Errorf("hash repository file %q: %w", name, readErr)
	}
	if closeErr != nil {
		return 0, "", fmt.Errorf("close repository file %q: %w", name, closeErr)
	}
	return size, hex.EncodeToString(hash.Sum(nil)), nil
}

func rejectUnexpectedFiles(root string, expected map[string]bool) error {
	var actual []string
	err := filepath.WalkDir(root, func(name string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.Type()&fs.ModeSymlink != 0 {
			return fmt.Errorf("repository contains symbolic link %q", name)
		}
		if entry.IsDir() {
			return nil
		}
		if !entry.Type().IsRegular() {
			return fmt.Errorf("repository contains non-regular file %q", name)
		}
		relative, err := filepath.Rel(root, name)
		if err != nil {
			return err
		}
		actual = append(actual, filepath.ToSlash(relative))
		return nil
	})
	if err != nil {
		return err
	}
	sort.Strings(actual)
	for _, name := range actual {
		if !expected[name] {
			return fmt.Errorf("repository contains unexpected file %q", name)
		}
		delete(expected, name)
	}
	if len(expected) != 0 {
		return errors.New("repository is missing files declared by its manifest")
	}
	return nil
}

func requireJSONEOF(decoder *json.Decoder) error {
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return errors.New("repository manifest contains more than one JSON value")
		}
		return fmt.Errorf("decode repository manifest: %w", err)
	}
	return nil
}

func verifyPyPIStructure(root string, manifest buildgraph.RepositoryManifest) ([]domain.Blob, error) {
	var blobs []domain.Blob
	for _, file := range manifest.Files {
		if strings.HasPrefix(file.Path, "simple/") {
			if path.Base(file.Path) != "index.html" {
				return nil, fmt.Errorf("unexpected PyPI index path %q", file.Path)
			}
			continue
		}
		parts := strings.Split(file.Path, "/")
		if len(parts) != 3 || parts[0] != "packages" || parts[1] != file.SHA256 || !pypi.IsDistributionFilename(parts[2]) {
			return nil, fmt.Errorf("unexpected PyPI repository path %q", file.Path)
		}
		name := filepath.Join(root, filepath.FromSlash(file.Path))
		packageFile, err := os.Open(name)
		if err != nil {
			return nil, fmt.Errorf("open PyPI package %q: %w", file.Path, err)
		}
		facts, inspectErr := pypi.Inspect(parts[2], packageFile, file.Size)
		closeErr := packageFile.Close()
		if inspectErr != nil {
			return nil, inspectErr
		}
		if closeErr != nil {
			return nil, fmt.Errorf("close PyPI package %q: %w", file.Path, closeErr)
		}
		blobs = append(blobs, domain.Blob{Filename: parts[2], Size: file.Size, SHA256: file.SHA256, Facts: facts})
	}
	expectedArtifact, err := pypi.Build(blobs)
	if err != nil {
		return nil, fmt.Errorf("rebuild PyPI structure: %w", err)
	}
	generatedAt, err := time.Parse(time.RFC3339, manifest.GeneratedAt)
	if err != nil {
		return nil, err
	}
	_, expectedManifest, err := buildgraph.Finalize(expectedArtifact, generatedAt)
	if err != nil {
		return nil, fmt.Errorf("finalize expected PyPI structure: %w", err)
	}
	if !reflect.DeepEqual(expectedManifest, manifest) {
		return nil, errors.New("PyPI indexes or verification metadata do not match package bytes")
	}
	return blobs, nil
}

func verifyDebStructure(root string, manifest buildgraph.RepositoryManifest) ([]domain.Blob, error) {
	var blobs []domain.Blob
	for _, file := range manifest.Files {
		if strings.HasPrefix(file.Path, "dists/") {
			continue
		}
		if !strings.HasPrefix(file.Path, "pool/") || !deb.IsPackageFilename(path.Base(file.Path)) {
			return nil, fmt.Errorf("unexpected Debian repository path %q", file.Path)
		}
		name := filepath.Join(root, filepath.FromSlash(file.Path))
		packageFile, err := os.Open(name)
		if err != nil {
			return nil, fmt.Errorf("open Debian package %q: %w", file.Path, err)
		}
		facts, inspectErr := deb.Inspect(path.Base(file.Path), packageFile, file.Size)
		closeErr := packageFile.Close()
		if inspectErr != nil {
			return nil, inspectErr
		}
		if closeErr != nil {
			return nil, fmt.Errorf("close Debian package %q: %w", file.Path, closeErr)
		}
		md5Value, sha1Value, err := legacyChecksums(name)
		if err != nil {
			return nil, err
		}
		blobs = append(blobs, domain.Blob{
			Filename: path.Base(file.Path),
			Size:     file.Size,
			MD5:      md5Value,
			SHA1:     sha1Value,
			SHA256:   file.SHA256,
			Facts:    facts,
		})
	}
	generatedAt, err := time.Parse(time.RFC3339, manifest.GeneratedAt)
	if err != nil {
		return nil, err
	}
	expectedArtifact, err := deb.Build(blobs, deb.BuildOptions{
		Suite:         manifest.Install.Suite,
		Component:     manifest.Install.Component,
		Architectures: manifest.Install.Architectures,
		GeneratedAt:   generatedAt,
	})
	if err != nil {
		return nil, fmt.Errorf("rebuild Debian structure: %w", err)
	}
	_, expectedManifest, err := buildgraph.Finalize(expectedArtifact, generatedAt)
	if err != nil {
		return nil, fmt.Errorf("finalize expected Debian structure: %w", err)
	}
	if !reflect.DeepEqual(expectedManifest, manifest) {
		return nil, errors.New("Debian indexes or verification metadata do not match package bytes")
	}
	return blobs, nil
}

func verifyHelmStructure(root string, manifest buildgraph.RepositoryManifest) ([]domain.Blob, error) {
	var blobs []domain.Blob
	for _, file := range manifest.Files {
		if file.Path == "index.yaml" {
			continue
		}
		parts := strings.Split(file.Path, "/")
		if len(parts) != 3 || parts[0] != "charts" || parts[1] != file.SHA256 || !helm.IsChartFilename(parts[2]) {
			return nil, fmt.Errorf("unexpected Helm repository path %q", file.Path)
		}
		name := filepath.Join(root, filepath.FromSlash(file.Path))
		chartFile, err := os.Open(name)
		if err != nil {
			return nil, fmt.Errorf("open Helm chart %q: %w", file.Path, err)
		}
		facts, inspectErr := helm.Inspect(parts[2], chartFile, file.Size)
		closeErr := chartFile.Close()
		if inspectErr != nil {
			return nil, inspectErr
		}
		if closeErr != nil {
			return nil, fmt.Errorf("close Helm chart %q: %w", file.Path, closeErr)
		}
		blobs = append(blobs, domain.Blob{Filename: parts[2], Size: file.Size, SHA256: file.SHA256, Facts: facts})
	}
	generatedAt, err := time.Parse(time.RFC3339, manifest.GeneratedAt)
	if err != nil {
		return nil, err
	}
	expectedArtifact, err := helm.Build(blobs, helm.BuildOptions{GeneratedAt: generatedAt})
	if err != nil {
		return nil, fmt.Errorf("rebuild Helm structure: %w", err)
	}
	_, expectedManifest, err := buildgraph.Finalize(expectedArtifact, generatedAt)
	if err != nil {
		return nil, fmt.Errorf("finalize expected Helm structure: %w", err)
	}
	if !reflect.DeepEqual(expectedManifest, manifest) {
		return nil, errors.New("Helm index or verification metadata does not match chart bytes")
	}
	return blobs, nil
}

func legacyChecksums(name string) (string, string, error) {
	file, err := os.Open(name)
	if err != nil {
		return "", "", err
	}
	md5Hash := md5.New()
	sha1Hash := sha1.New()
	_, readErr := io.Copy(io.MultiWriter(md5Hash, sha1Hash), file)
	closeErr := file.Close()
	if readErr != nil {
		return "", "", readErr
	}
	if closeErr != nil {
		return "", "", closeErr
	}
	return hex.EncodeToString(md5Hash.Sum(nil)), hex.EncodeToString(sha1Hash.Sum(nil)), nil
}

func snapshotRepository(ctx context.Context, source string, manifest buildgraph.RepositoryManifest) (string, error) {
	snapshot, err := os.MkdirTemp("", ".snailmail-repository-*")
	if err != nil {
		return "", fmt.Errorf("create repository snapshot: %w", err)
	}
	if err := os.Chmod(snapshot, 0o755); err != nil {
		_ = os.RemoveAll(snapshot)
		return "", fmt.Errorf("make repository snapshot readable: %w", err)
	}
	keep := false
	defer func() {
		if !keep {
			_ = os.RemoveAll(snapshot)
		}
	}()
	files := make([]buildgraph.ManifestFile, 0, len(manifest.Files)+1)
	files = append(files, manifest.Files...)
	manifestInfo, err := os.Lstat(filepath.Join(source, buildgraph.ManifestFilename))
	if err != nil {
		return "", err
	}
	if !manifestInfo.Mode().IsRegular() || manifestInfo.Size() > maxManifestSize {
		return "", errors.New("repository manifest is not a bounded regular file")
	}
	files = append(files, buildgraph.ManifestFile{Path: buildgraph.ManifestFilename, Size: manifestInfo.Size()})
	for _, file := range files {
		if err := ctx.Err(); err != nil {
			return "", err
		}
		name := filepath.Join(source, filepath.FromSlash(file.Path))
		info, err := os.Lstat(name)
		if err != nil {
			return "", err
		}
		if !info.Mode().IsRegular() || info.Size() != file.Size {
			return "", fmt.Errorf("repository file %q changed before snapshot", file.Path)
		}
		target := filepath.Join(snapshot, filepath.FromSlash(file.Path))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return "", err
		}
		if err := copyFile(name, target, file.Size); err != nil {
			return "", err
		}
	}
	keep = true
	return snapshot, nil
}

func copyFile(sourceName, targetName string, expectedSize int64) error {
	source, err := os.Open(sourceName)
	if err != nil {
		return err
	}
	destination, err := os.OpenFile(targetName, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		_ = source.Close()
		return err
	}
	written, copyErr := io.Copy(destination, io.LimitReader(source, expectedSize+1))
	closeDestinationErr := destination.Close()
	closeSourceErr := source.Close()
	if copyErr != nil {
		return copyErr
	}
	if written != expectedSize {
		return fmt.Errorf("repository file %q changed while snapshotting", sourceName)
	}
	if closeDestinationErr != nil {
		return closeDestinationErr
	}
	return closeSourceErr
}
