package testutil

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

func Deb(name, version, architecture string, dependencies []string) ([]byte, string, error) {
	control := "Package: " + name + "\n" +
		"Version: " + version + "\n" +
		"Section: utils\n" +
		"Priority: optional\n" +
		"Architecture: " + architecture + "\n" +
		"Installed-Size: 1\n" +
		"Maintainer: Snailmail Test <test@example.invalid>\n"
	if len(dependencies) != 0 {
		control += "Depends: " + strings.Join(dependencies, ", ") + "\n"
	}
	control += "Description: deterministic test package\n generated by snailmail tests\n"
	controlArchive, err := tarGzip(map[string]string{"./control": control})
	if err != nil {
		return nil, "", err
	}
	dataArchive, err := tarGzip(map[string]string{"./usr/share/" + name + "/installed.txt": version + "\n"})
	if err != nil {
		return nil, "", err
	}

	var archive bytes.Buffer
	archive.WriteString("!<arch>\n")
	for _, member := range []struct {
		name    string
		content []byte
	}{
		{name: "debian-binary", content: []byte("2.0\n")},
		{name: "control.tar.gz", content: controlArchive},
		{name: "data.tar.gz", content: dataArchive},
	} {
		if len(member.name)+1 > 16 {
			return nil, "", fmt.Errorf("ar member name %q is too long", member.name)
		}
		header := fmt.Sprintf("%-16s%-12d%-6d%-6d%-8o%-10d`\n", member.name+"/", 0, 0, 0, 0o100644, len(member.content))
		if len(header) != 60 {
			return nil, "", fmt.Errorf("ar header has length %d", len(header))
		}
		archive.WriteString(header)
		archive.Write(member.content)
		if len(member.content)%2 != 0 {
			archive.WriteByte('\n')
		}
	}
	filename := fmt.Sprintf("%s_%s_%s.deb", name, version, architecture)
	return archive.Bytes(), filename, nil
}

func WriteDeb(directory, name, version, architecture string, dependencies []string) (string, error) {
	content, filename, err := Deb(name, version, architecture, dependencies)
	if err != nil {
		return "", err
	}
	filename = filepath.Join(directory, filename)
	if err := os.WriteFile(filename, content, 0o644); err != nil {
		return "", err
	}
	return filename, nil
}

func tarGzip(files map[string]string) ([]byte, error) {
	var compressed bytes.Buffer
	gzipWriter, err := gzip.NewWriterLevel(&compressed, gzip.BestCompression)
	if err != nil {
		return nil, err
	}
	gzipWriter.Header.ModTime = time.Unix(0, 0).UTC()
	gzipWriter.Header.OS = 255
	tarWriter := tar.NewWriter(gzipWriter)
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	writtenDirectories := make(map[string]bool)
	for _, name := range names {
		parts := strings.Split(strings.TrimPrefix(name, "./"), "/")
		directory := "."
		for _, part := range parts[:len(parts)-1] {
			directory += "/" + part
			if writtenDirectories[directory] {
				continue
			}
			if err := tarWriter.WriteHeader(&tar.Header{
				Name: directory + "/", Mode: 0o755, Typeflag: tar.TypeDir,
				ModTime: time.Unix(0, 0).UTC(), Format: tar.FormatGNU,
			}); err != nil {
				return nil, err
			}
			writtenDirectories[directory] = true
		}
		content := []byte(files[name])
		header := &tar.Header{
			Name:     name,
			Mode:     0o644,
			Size:     int64(len(content)),
			ModTime:  time.Unix(0, 0).UTC(),
			Typeflag: tar.TypeReg,
			Format:   tar.FormatGNU,
		}
		if err := tarWriter.WriteHeader(header); err != nil {
			return nil, err
		}
		if _, err := tarWriter.Write(content); err != nil {
			return nil, err
		}
	}
	if err := tarWriter.Close(); err != nil {
		return nil, err
	}
	if err := gzipWriter.Close(); err != nil {
		return nil, err
	}
	return compressed.Bytes(), nil
}
