package rpm

import (
	"os"
	"strconv"
	"strings"
	"testing"
)

// testdata/vercmp.txt is the answer real rpm gives, generated by asking it:
//
//	rpm --eval '%{lua: print(rpm.vercmp("<left>", "<right>"))}'
//
// Comparing against a reimplementation of the algorithm would only prove the
// two agree; comparing against rpm proves this orders packages the way the
// client that installs them does.
//
// rpm.vercmp compares whole EVR strings rather than raw segments, which is what
// "1.0" against "1-0" reveals: the second is version 1 release 0, so the first
// is the higher version even though a segment-by-segment walk calls them equal.
func TestCompareVersionsAgreesWithRPM(t *testing.T) {
	content, err := os.ReadFile("testdata/vercmp.txt")
	if err != nil {
		t.Fatal(err)
	}
	checked := 0
	for _, line := range strings.Split(strings.TrimSpace(string(content)), "\n") {
		fields := strings.Fields(line)
		if len(fields) != 3 {
			t.Fatalf("unusable golden line %q", line)
		}
		want, err := strconv.Atoi(fields[2])
		if err != nil {
			t.Fatalf("unusable golden result in %q", line)
		}
		got, err := CompareVersions(fields[0], fields[1])
		if err != nil {
			t.Errorf("CompareVersions(%q, %q): %v", fields[0], fields[1], err)
			continue
		}
		if got != want {
			t.Errorf("CompareVersions(%q, %q) = %d, rpm says %d", fields[0], fields[1], got, want)
		}
		checked++
	}
	if checked < 30 {
		t.Fatalf("only %d comparisons were checked", checked)
	}
	t.Logf("agreed with rpm on %d comparisons", checked)
}
